# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: nft-devnet-0
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        nft-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.nft-devnet-0.ethpandaops.io
    clientArgs:
      networks:
        nft-devnet-0:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://6b05942ae9375a8a8ae108371a801aad6bd63ae6ff5748e7640541e4f31f93833ca064b39dd32e625f5579c27f2ddb35db09e3a5cb8269281efc50c41a9e1cfd@192.81.208.55:30303?discport=30303,enode://2b40c68d6ceda0a257aba05c18832e2b6d533ade756086a0cd6b9412638c8780d1d99732efd8303939085423e00ce161cf0451062a38bde9864a16957b342221@152.42.253.252:30303?discport=30303,enode://0fcc2e7644116adaf145d0f48413ba94ce75ca99ff1c2a3fd1c27ea72a334d9d823fc38de2724651f8b80928be8ace375bbf64d22066750fa4e49a0176ca5e2a@209.97.182.132:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.ethstats_secret}>@ethstats.nft-devnet-0.ethpandaops.io:443
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://6b05942ae9375a8a8ae108371a801aad6bd63ae6ff5748e7640541e4f31f93833ca064b39dd32e625f5579c27f2ddb35db09e3a5cb8269281efc50c41a9e1cfd@192.81.208.55:30303?discport=30303,enode://2b40c68d6ceda0a257aba05c18832e2b6d533ade756086a0cd6b9412638c8780d1d99732efd8303939085423e00ce161cf0451062a38bde9864a16957b342221@152.42.253.252:30303?discport=30303,enode://0fcc2e7644116adaf145d0f48413ba94ce75ca99ff1c2a3fd1c27ea72a334d9d823fc38de2724651f8b80928be8ace375bbf64d22066750fa4e49a0176ca5e2a@209.97.182.132:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.nft-devnet-0.ethpandaops.io/api/
              - --log=INFO
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7010705318
              - --syncmode=full
              - --bootnodes=enode://6b05942ae9375a8a8ae108371a801aad6bd63ae6ff5748e7640541e4f31f93833ca064b39dd32e625f5579c27f2ddb35db09e3a5cb8269281efc50c41a9e1cfd@192.81.208.55:30303?discport=30303,enode://2b40c68d6ceda0a257aba05c18832e2b6d533ade756086a0cd6b9412638c8780d1d99732efd8303939085423e00ce161cf0451062a38bde9864a16957b342221@152.42.253.252:30303?discport=30303,enode://0fcc2e7644116adaf145d0f48413ba94ce75ca99ff1c2a3fd1c27ea72a334d9d823fc38de2724651f8b80928be8ace375bbf64d22066750fa4e49a0176ca5e2a@209.97.182.132:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.ethstats_secret}>@ethstats.nft-devnet-0.ethpandaops.io
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7010705318
              - --db.size.limit=500GB
              - --bootnodes=enode://6b05942ae9375a8a8ae108371a801aad6bd63ae6ff5748e7640541e4f31f93833ca064b39dd32e625f5579c27f2ddb35db09e3a5cb8269281efc50c41a9e1cfd@192.81.208.55:30303?discport=30303,enode://2b40c68d6ceda0a257aba05c18832e2b6d533ade756086a0cd6b9412638c8780d1d99732efd8303939085423e00ce161cf0451062a38bde9864a16957b342221@152.42.253.252:30303?discport=30303,enode://0fcc2e7644116adaf145d0f48413ba94ce75ca99ff1c2a3fd1c27ea72a334d9d823fc38de2724651f8b80928be8ace375bbf64d22066750fa4e49a0176ca5e2a@209.97.182.132:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.ethstats_secret}>@ethstats.nft-devnet-0.ethpandaops.io
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-LK4QMuWGUj0-jV_jRRCkIXMLuo3pxCsXbg--YpLB6l0COdhYH_nJeDb8Imm5TWvamT0I8-R3GRoSBmPIjqYV6pE0zMIh2F0dG5ldHOIAAAAGAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhMBR0DeJc2VjcDI1NmsxoQN-uOmCDNhWsEyROND46ktbg75nQxZUZducCThKyPxe7oN0Y3CCIyiDdWRwgiMo,enr:-LK4QDV6g2SnjvtWLq_j-ySKFMijf-tKU7E5uONuiP7np4i6fzKnyTXJ6qoZT0A5tIYbahJa_CCvKm-snxrNbLStsA0Ih2F0dG5ldHOIAwAAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhJgq_fyJc2VjcDI1NmsxoQIs093LJYvnQn0dcgJpSiufiy-GZRiMOMaJ-A43g-6vAIN0Y3CCIyiDdWRwgiMo,enr:-LK4QOqnjcjLw8FpGLFZHvj-ztxz_farE2uMwYc9VBSgaOCWSOatpUhiInxLd2gL8xJYM5BXViEI7ph1XYXnqcKSRqAIh2F0dG5ldHOIAADAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhNFhtoSJc2VjcDI1NmsxoQIDbQHDB8rwsjWaO-hHC8RnEnZEkTUP2vMM_IeXH5QYMIN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-LK4QMuWGUj0-jV_jRRCkIXMLuo3pxCsXbg--YpLB6l0COdhYH_nJeDb8Imm5TWvamT0I8-R3GRoSBmPIjqYV6pE0zMIh2F0dG5ldHOIAAAAGAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhMBR0DeJc2VjcDI1NmsxoQN-uOmCDNhWsEyROND46ktbg75nQxZUZducCThKyPxe7oN0Y3CCIyiDdWRwgiMo,enr:-LK4QDV6g2SnjvtWLq_j-ySKFMijf-tKU7E5uONuiP7np4i6fzKnyTXJ6qoZT0A5tIYbahJa_CCvKm-snxrNbLStsA0Ih2F0dG5ldHOIAwAAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhJgq_fyJc2VjcDI1NmsxoQIs093LJYvnQn0dcgJpSiufiy-GZRiMOMaJ-A43g-6vAIN0Y3CCIyiDdWRwgiMo,enr:-LK4QOqnjcjLw8FpGLFZHvj-ztxz_farE2uMwYc9VBSgaOCWSOatpUhiInxLd2gL8xJYM5BXViEI7ph1XYXnqcKSRqAIh2F0dG5ldHOIAADAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhNFhtoSJc2VjcDI1NmsxoQIDbQHDB8rwsjWaO-hHC8RnEnZEkTUP2vMM_IeXH5QYMIN0Y3CCIyiDdWRwgiMo
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --bootstrap-node=enr:-LK4QMuWGUj0-jV_jRRCkIXMLuo3pxCsXbg--YpLB6l0COdhYH_nJeDb8Imm5TWvamT0I8-R3GRoSBmPIjqYV6pE0zMIh2F0dG5ldHOIAAAAGAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhMBR0DeJc2VjcDI1NmsxoQN-uOmCDNhWsEyROND46ktbg75nQxZUZducCThKyPxe7oN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-LK4QDV6g2SnjvtWLq_j-ySKFMijf-tKU7E5uONuiP7np4i6fzKnyTXJ6qoZT0A5tIYbahJa_CCvKm-snxrNbLStsA0Ih2F0dG5ldHOIAwAAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhJgq_fyJc2VjcDI1NmsxoQIs093LJYvnQn0dcgJpSiufiy-GZRiMOMaJ-A43g-6vAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-LK4QOqnjcjLw8FpGLFZHvj-ztxz_farE2uMwYc9VBSgaOCWSOatpUhiInxLd2gL8xJYM5BXViEI7ph1XYXnqcKSRqAIh2F0dG5ldHOIAADAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhNFhtoSJc2VjcDI1NmsxoQIDbQHDB8rwsjWaO-hHC8RnEnZEkTUP2vMM_IeXH5QYMIN0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-LK4QMuWGUj0-jV_jRRCkIXMLuo3pxCsXbg--YpLB6l0COdhYH_nJeDb8Imm5TWvamT0I8-R3GRoSBmPIjqYV6pE0zMIh2F0dG5ldHOIAAAAGAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhMBR0DeJc2VjcDI1NmsxoQN-uOmCDNhWsEyROND46ktbg75nQxZUZducCThKyPxe7oN0Y3CCIyiDdWRwgiMo,enr:-LK4QDV6g2SnjvtWLq_j-ySKFMijf-tKU7E5uONuiP7np4i6fzKnyTXJ6qoZT0A5tIYbahJa_CCvKm-snxrNbLStsA0Ih2F0dG5ldHOIAwAAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhJgq_fyJc2VjcDI1NmsxoQIs093LJYvnQn0dcgJpSiufiy-GZRiMOMaJ-A43g-6vAIN0Y3CCIyiDdWRwgiMo,enr:-LK4QOqnjcjLw8FpGLFZHvj-ztxz_farE2uMwYc9VBSgaOCWSOatpUhiInxLd2gL8xJYM5BXViEI7ph1XYXnqcKSRqAIh2F0dG5ldHOIAADAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhNFhtoSJc2VjcDI1NmsxoQIDbQHDB8rwsjWaO-hHC8RnEnZEkTUP2vMM_IeXH5QYMIN0Y3CCIyiDdWRwgiMo
              - --allow-insecure-genesis-sync
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-LK4QMuWGUj0-jV_jRRCkIXMLuo3pxCsXbg--YpLB6l0COdhYH_nJeDb8Imm5TWvamT0I8-R3GRoSBmPIjqYV6pE0zMIh2F0dG5ldHOIAAAAGAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhMBR0DeJc2VjcDI1NmsxoQN-uOmCDNhWsEyROND46ktbg75nQxZUZducCThKyPxe7oN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-LK4QDV6g2SnjvtWLq_j-ySKFMijf-tKU7E5uONuiP7np4i6fzKnyTXJ6qoZT0A5tIYbahJa_CCvKm-snxrNbLStsA0Ih2F0dG5ldHOIAwAAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhJgq_fyJc2VjcDI1NmsxoQIs093LJYvnQn0dcgJpSiufiy-GZRiMOMaJ-A43g-6vAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-LK4QOqnjcjLw8FpGLFZHvj-ztxz_farE2uMwYc9VBSgaOCWSOatpUhiInxLd2gL8xJYM5BXViEI7ph1XYXnqcKSRqAIh2F0dG5ldHOIAADAAAAAAACEZXRoMpBu_IrNYBBVED9CDwAAAAAAgmlkgnY0gmlwhNFhtoSJc2VjcDI1NmsxoQIDbQHDB8rwsjWaO-hHC8RnEnZEkTUP2vMM_IeXH5QYMIN0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: docker.ethquokkaops.io/dh/ethereum/client-go
      tag: v1.14.12
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: nft-devnet-0
      testnet: nft-devnet-0
      ethereum_network: nft-devnet-0
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.nft-devnet-0.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.nft-devnet-0.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.nft-devnet-0.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.nft-devnet-0.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethereum/client-go:v1.14.12
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/consensys/teku
      tag: 24.10
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: nft-devnet-0
      testnet: nft-devnet-0
      ethereum_network: nft-devnet-0
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.nft-devnet-0.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.nft-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.nft-devnet-0.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.nft-devnet-0.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.nft-devnet-0.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.nft-devnet-0.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
