cl_bootnode_privkey: ENC[AES256_GCM,data:ywhGk8vFMF6ishOKGWMfSn0IxJttDiSBqaHgserxIamQvRMzJPcmMvAStVfMZB7XBHGyiWLy9vvDFhhQzBiocg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:d2jUPi/+szwu4fkG1UuYKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:18:36Z"
    mac: ENC[AES256_GCM,data:OvHF2KM4DeBqRrBC2bhcpCrUbW2mwIvt+6+nwXld/qoDhgTxT8DBXGAfFY9wE172uElnV6O2bHGfgwCVX121Jg6d1rYzvcXrXuLaaTqLCTjy3xAkE0GrjJpXDAzhghsY95NU+n3u5Rz+49SffK/sR/dqRyNsASsW64eTzdMvXng=,iv:5di/nwLQieMrIxn6IEOP1UcJjick+X1l0kLka2e/72w=,tag:7jfPRLfWT2WiwllOfvxtEA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//cMjTFvQGDJPNogbtTjVmP6f61BkrxWPSHr5lQsaDf0bH
            EG0bRL03sCGEz7sLzqKL15TjV0Cf1Da4c1l5TyKDDiJne7uhKVaMGKHQ3WYgkN3K
            NKYl6ocg9DZglwVUAgcolZ/JRkZfYL/EJUWyrubarmevF1ME5IMPD2ZrT47N3x+3
            xwT4i1PGq/23G2duEmyTceMAYwEyAQP9BZW5fXv/lvix0Lf96obQl7YPt/you7LD
            GrrOHa2D9gllJouAkgykjUUTDqNwwDo56rABCY50MU2jiXuhkp7EcRX67ByFSA9W
            0VS8CbehgAGF/Slctkb6TIlhRefvKCUHD1dQjlZqFdoRZkjpuH+4ZVRbrN2rAQQI
            bY8VaT8/YBy4ehoXkrVeV/Rurulnp5wjwqtrgtkSyUPgg+ZKaYjkdrBWl+DDe+d3
            f/GR7n9arROrHGDQ8lX9l+LYYWEfSCsR6P8Song98Od1JjVprSy0L1qfa5xuHrcT
            wGbjvA1nTy47cZXOBpnkvf5PJCfQioyy1dJvY3oY9uO4+k0GpmlGf64yy9O5FAYn
            //BIJFxjbxTh9LgSqVwbLRFtE7u+pKpQMI4ARg/Hkh3QePOvnP1E13jiIZw87jS9
            7V13G0QZS9xLTA0P8JSYd4FRMYTNcHgcbKfaxjiYKea9PFuuvxbSeFMU1+HQlSDS
            UQHQ3qYnXBbpw2iFByWK3CWlowA/GqitKbJPScwscjyedkU3W+U47czOrX3Kaffw
            IBR+s/fk/aqdidirOIGYxbn7JC5KdYxZRwLcLN0cHCNnew==
            =Oa6w
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAz+sm032RDQglz3Ok9M9IeNF2hPAv6iZV1FKeNGlvY9L0
            GwTQTcDolAdCuYlKpuvtxNVNEv8JYCp9Dvzr+hZBQAwhzJhQ2SjZF3/zqIQwFuSa
            +T73fw76IVoE0FMIMB6Fl8fPkcZT4hfan4/u4FVJQeQLRUrhEVgecA2MpONfgrr6
            5Y7WbOMlBUQbgcbH9sEafGsKJKNd96EgRbtQx6TqH34AXNdzJ42SU/LbBvI7e2qV
            kZN75SMCS6pjygz3a7xRvGPx0+WuxyfLbkij0tsXlYe9rWpRnlAdFhQ+mad6c6YH
            g+o1OXE9vloNw/Z+QKmSi9j4slDdVaJeUguzA9foI30neJHdMu6zgfplX8KbNHwk
            6TCJsN0B+zLfvbOaFOhatN9zzCOiNIrtnyZQUNk4ixzO3eufE/owDD9rRW9vs4uS
            RYnKSXi4gqJnmhMmHjRU/O5xm+QLDvcI0H+9lv1j8LLWsfJ92GjEZHFyNArWoqR7
            HwTlAqyV04TQ+9Qrxad50sMCSWCR5Kik1WkHZatCuXCNOi6kwF+5sVwbLooHcAyZ
            YBXSJ9f9mvrCpYZdesuNxgQsTnqI4/CsIw8JAivumVnioITmuBCg43q1ZpV4ik/F
            T09r12c3hvTrMgzvSnsAO0Psmei6V3pdvYpnyS4OOcHNpI+qLDSbeHeEK0bJR8rS
            UQFTnHwU/jmjvKzuodNNQI68JCdkbRcY4tKje35FKD37YbXBplupADZpQ9GO3T3O
            BTatM+Xn44szgmGgirqCrDKBO3r25/4lySXnD1hOG0K/Aw==
            =6U6J
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ/+IGBtzh84cypoJCTRjRvJNB3iS5APaEu2gBZOrV1dIp4C
            UFfzm1VyTYhHf3Upt0ub11aofe2QAsnE6b8fqoGQC/ZSVQTdZrD6RTfDsgT7bLrg
            jLXHfXsrknC9HqMT299zIYgoqAs3UcCiYGx0D4zxeCE16EObGytExdh+skpG6f8R
            0xMcGaOfo0sQrzn7QHd2Rp/UZjKHV8uuZuf2qtmWJm/CqzatMergrVAwH9hfKov/
            U0LP26dMdJfqGswTZvnAOj6YPKNUMjNtSmNDQf3xDaFq/1ToAu4ajXwL66J8YP/j
            T48+9hkPlfW7EC3t8MY+vwN5/IX70h+0litZZDTQRhszAO8wxSiz1H8ln/qH0V8K
            7mTalC/1ujCYQ/800uja7nzA9o2nhs5uc83jwGKf8M9PqWv+bXr/UtwF0Lu73igP
            YG9a+MBef+V3kuOF8COvA1X+YLy5tnpWJFrIzXtFBnbLsQOq2iNniazWLF2enZG1
            J/YRhZ7bePJ/ftly/EKfvKKhEBUvKFNwAWlcwLdREGOY8vA5lhZTQu4HuFyecG0t
            2lHFxFKrYZiOEj8NQNcVdjpAeFg5KmheleDEcykr9Ah1JX6kEt8Y3VvNfodhqH9l
            dPaE8WAQO4kdXa64wCFkVIDyles54Rx7RNoh1Ps6odNvjILp82beI8VjavhG5lrS
            UQEq/8orP2hGucepAY3MSSUyWTYHKwlUzR1+JdVwA3dCWqIiPelGtcRtWG3tI52v
            dxiJJscRA6Bhzd/WJPVJAdMs+JCbPlfI31o6OHa6DU3v6w==
            =CEiQ
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ//axgXVtxoxfBIjWore0dn6PZfOugRSWFdUWzjgL2XtRyp
            vwdzmbJxN7h1iJ0uje4WvYq/9RjWfYHpOz/fV2h7SZnB9M2eK7RXTXpfcrkjEMdQ
            PG3iqgzxFMz8YVFaff5Sp+EUWAbnRzF9kWX/3Pd8xYjgESSu0nyEMsXlMbPIdovw
            76jmZJmwn8PS1JrTSmt2bvVKXXDOq8AvShayr7r6J6Xa5q5Hf2LrQSB18P4U01DZ
            /GCVay1bzYS68ZYFxws1OoJmx+RWJOA623QkBNKEXFiRwqbSxa953Vf0Oyqr0WPK
            2xqq7l/KIiCaHLCjS/zzo/SAtvEme+U2vuEXibFRGlUc/v8f8nMVn58Fn/uF4MX5
            Uoc57exw5W6NRY9y1hyCfGTbgTc4LLDIsfi48ySDws5Ed99QwLtu006/fNHMRe5X
            ni+pUKomwks7gdfiAVNYA+8WqegWpiV4qz62cXxq5FPuFHKQUHxDOEz+zHiNLR9g
            v49FTVacSqKleQ6Esa6hdUzc+/l5e31zB08/xxGVPEijH4uBa6Dd80R/FEdR6j9r
            WNGJ2ueJmtOhb0tc//yWrhAqxIT1Mg/NyZPayQXLqGSbTygmb427xTQgCgHvpI0y
            dcC9neepPsohV1udWpTPKCt4g8g0G/jyua4TBAvI2gXz66WHnCThdQMJ4TzQty/S
            UQEf6WHEJhEfXAxkGvPcg8gFj2gpDQGhSF4pzdpYuUTRqir3rm9NsS0o7d5lFPyY
            TIXkNOYH2Ol9lD2/qwqWnZDsyquABc4Bz52aQusskoBxLw==
            =wAQu
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQgAm0k0YA3oHVet3pfim6Yy5LkMwxsZfUYJ3wXQTCB1kF5K
            EmTiOFmO8yPrRkxmhyoAFRlIGO0w8FqShLP6GLpWoqkYeQRqNUh/rVMyldJ2TXfc
            iZ4oQZz/aqLzNCAJaPClsziLzvVRU8/WMvXvcHkiPKmmlpbvdO2uZHDJQZSHBR/K
            GZ9zscGn4ihs0XKvSyI1kHCOE9PChgG4ffP4FAbUGidh1FRdHmR8v0kY1blM/JyL
            U9CuD4QeR7UKL9YqVWs6Xp20+7j6xIbWYtTI8KLgBXhD/GgljclxNzHI6x+N8Mb0
            aaM7Gs7GnLBQvmXGQMzfimlCHOjRW054hGLw0kzY1dJRAafHK+6ZwHYQCkYQeco3
            TpQ9iYK2pkDhuKLaTQZbVWeZ6q/BRqu9/ZmZp++zBoG9uVhX0oAvQB1zikuSRAY8
            slkkOUTqndUQVY6uzV1Qw4Iy
            =z0Am
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//eQ4gXk5OpIWAlFzd+IAs10lDZJSoYPfSfNg2Sx0sdZw4
            vAEpuy6y/57rvX7qGusC4LmdqkJSMA+oeSzxE0MUPuKmgRC0JkXzHlb9T33rQpyT
            GJpIDw4fH27r+7BxAcxW73yeAFQ+06NLHUGV8dQ//5DFnaF1tB9upttdw+/Gmrpp
            bP9f/mD0thqa7IGAmlkrMYCxDb+p5N94Nh4cjkB54BqAo/Drd1pLYhpXHiifUSsz
            vU8UyJJp05xwLSBI/ydtUY64eKRw2a8f9zGS6TE06A/LhFygSyT2i69EU4cPYiwD
            isVXYCvi8vwBZATqcod4JGl2sLlS4vYS+OSKYvrXGm6Qm7sC47shQ/8oxL+it8fk
            4wfx2QoHbhmqG+M6ybidOXBEbUv9POzB0V8seZ4eWLcy+gU509Zqy4O/SKw/3e5/
            bWWSKSd7AOojeg2GdI/rY0IB7bmoQkU+uRx4JF7XuEPcaXwn+J/ob2lBC6ZlwNuV
            EMXQdJjf5RBNvVnUqT0HZUKdPPxFlyj0TI/e47DTDHBKqMs2yBqBEVHNHMIt533S
            Ky80IhqQxjuJIA7GmlNbi093j4gcixKZGjQo0Tgoqz/ZHquThINSaE09DMAMLdZX
            1p5QU/ETCikz4UNRqJl5oOOwfvFB8SFvYsSPN8QpxR5eZ7JFKsifQiXrW3/eJF3S
            UQEnhZumu37bLJBngQoujdwhZjTIrGWAnqge9yMO46+uFr1zbkDMnZIvEtdnAnxz
            ymjWRCJzla/rDmX12ngr9wFIENs7aTTK+rtIUF2CQ5Q7ZA==
            =hA6M
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/+JCdPaDSPattg7ujnjMtTniQ3aUgubtF/buAwmilgGmZt
            3vsrvzkdE5hJ8z36P5cfaunKoM8xHv9YwNUw7y256EZSJjCiFhDW89J7vyyJmyAZ
            ccYyvkW+OIGsCEkt8h8wbRszrAoMTa5T5mISEpgyOUZuDZYU5L33TJqzAydHLRgB
            2uLBKTFAqG7p6yMlt4eLoSreOYV651CfKfEFe1/MwW5bhEFy7svpkfNoOv4atU3a
            xxzNHWbXHTinv0Vqgr0dmn62H3jOiBnYwiLb0dA3eyYDiKXoezhJpRTfAIi2xfIY
            4LXsA+zSJlm3qgG9GFYy9YWmQ+7BccyIbSQwKfaa+7tbgzUFNyJ+rxN12jqdG6w+
            TJscNYpcol799rhXeN/8UazXqDhigydQCw9kODfVvgnkM/D2RkCQ2JL/eVpSO5Y0
            30ozQDF+o1FcO7K+Ujn6WJjGF+HsWlHXi3FPC+8O/nZbSUDqLD3mb097z0vn5hnF
            mjuivchLAHIw1N3fqp81HQ9+mRILWujocK0f/uEixqLs6Zx/r1JeQUXKh5uikllf
            I9H39GiaxVaqc8Xn1NAg39sBZbDwO7lAn3xidAZsPjFYq6L0su8tvexBRFIJw48k
            qO5mA/9mQF2DatvCMxVlQcZGEI+iqHjQ2Ut8k5YxR88wDewZdqUsVu9E74Vpre7S
            UQFNACtUUCCz4yW8QJ7knLCKGrW7+/bQr4f97ZKBSgfbV4yBXo+5RqmRgn/X1btU
            zEaYba/7XxGL8lDgtB1dXjSmBZ3IWwy0X9QEs65GEs/fXw==
            =0gak
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAKZq6ipquV6gjZChzn/flD6K92U/s9K7TA4rRgHBJ6QEw
            ypoF+etpgcrudtd6vPNVeLVWTRFqf9/8rEmOoJ3H6meZTbwnsKTc4QdRoOVVmO12
            1FsBCQIQcvJQQ34ad3PYOkXQqSdOZm/TmzGnYI9aD5aVT7/q3K5T6FZzR1H/Ojim
            h1tDh/kBYfv+I5dF325W/abWXqw4Lx0urnX9mSBHTtcOzNq97ntqty2Lu6+L
            =uYfk
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
