cl_bootnode_privkey: ENC[AES256_GCM,data:pLnih0aCxSlJfQa/XSPBHP+Eb9zYJmiGR8zeOmlwxYvP/hGNNi9d1BAxQ17wMOQMZMdnpbiVe0TYn1XZeygldg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:w457gcF2W0na9LsBLIpl3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:21:02Z"
    mac: ENC[AES256_GCM,data:gjbUF8i0m1GAf768uAVBHAcHLu+aA2M4+8aFoOpxnKsGc8nx3BPQG8dZY2782vm7K9H/bjU2c1D+ZKrmWAbV/onuNE+kqGBrzh+HRH33rqcsrT2ww/Eh7fIoUwtOLrVpV6daWnuKYasw8oW664vUnLnNZFgvqOyOLoNA11JQSf4=,iv:JAv2sAAyGi/50Yfrq66FvgRV6ldPPBPoyKFjrGvyaa0=,tag:y1zZkvKI7ox/lJSSHr+8BA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pARAAgfCu0yIlsxbgA/2qFG+Fbz8td/ULZXsIcOHRw3F3RJv4
            bXFINOqe0zOVWxhb5GkCsvOQuqpl9bLpn7LE6Ommus+xOk+4mq36RuGfPu3Cl0ha
            4kEm/HhD8I7p3cdCNiWl/wP8Hk8b4MWnWkU+n2LP3LoaPGEIPQtni4jsPYkug70a
            k+4ir+F4W5uo5FS/MmWPJMG3jsbI7WyxxfHbrEyE7u4jBBRAPZMo9DNagyJ91iqx
            49WdTp8zrqnDt8pSRNz6znOyTuJ9+zNlIPMkzf76JxQ2nvJGzNLBlFtkh5xLTWU5
            fsw36sA9FCEE8Hawb8DdrNqOwtqz7JFw5BM/SV1C9GZp5su+h1oAi29h1kgqyO1j
            o7Nb/mPi3ACRVHUTj8fBlubwKbDKrJUXxAgaOOZzShuShFM5gTSSJo/v//UNnwAS
            LieUOZvByhcH4sbew7ucPSjgvt3RcXLIVqS8aLAFnvOFvNF7Lut9ZbSaU6EB1AXU
            sAzJvBC4atRwT2Cd22XYrrtU1SsG57izQk7ZBYandubLFnob7PnBVaxPE/hrCbMc
            HJSx7h0vNBm2NGPP7JoBZBxSc/oCf/8ZT1AM7N25H/MgDcbCd2eOdAnJnRUWoZ6r
            wHdypVMdi6QQYKUtERaUJUuZwW2H0x5qPQrh4jEbKRKegSkzwKNxbtBbyRiUo8LS
            XgHW0ZAu6nqSfqeFs1nckjmdrQjwMwXzjaZkG3tkqGOf1uDvO2J0CDnTEzCqJRsY
            UUj2xDkjOQ6mqAwT8xkDiVkZEkqnM6gkyQNd5fhCkkx0Iy24ihiPXn696QfUGbw=
            =uLU6
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGAQ//YoyudhOV31Ihv4/ZSDLTmlNM0rWaxhHQOBJpRJ0pxsfk
            o50xd46iybJUL89D//z+TKmsLOx5IvxPCln4tp4ddd9UKY2vjJf8q984ngeOYcB4
            CWHA3dQDPZS6JgQUfrn+fMgUpNU7CnHLi3MNegttertDsq40QpeRg6JecQSDzVA2
            43oX/+qHSn6MX7FYaX+b1Bz5mNHyUxjeLsRR+OGGQZb/zs+QOCtYjFU7joa4lgLb
            0UO4VLCRiHvp7MqsTDB3vVASv64SQKQ2ine3DX4KDqgaAzQmtgCKDVas4Tai6T2N
            THqDjWC6lMUXx/+crbajJeWAtAIu5rwlRuSr6J25hwX7wT0eSCZIf7pMORQnXXIW
            wuc4uP1JoBmU+/eqdIYvWwZ+taeUcdexOAP1i8H3DFm5cqcbsm9M9ZA88WBD7gIa
            TvsZcFNQhy+deGYqmI4ef+lQw5mltTNFBDCWb/81ER+5B66q9+glfTWaE0pbo/8M
            Yp5naZNLjyv5ADDNDXlbO2tL5zgfMHUdKoIbzwbo1zpNZXf9KUPhcQJiZUUPgaE5
            AfvaGpEnww33A58X9EcfbUvMnMby/7zJEd33IiU9dqGnRV2guRoBKvZDRvgdHl4R
            Kc6k6quTjXaRMiJfmpKxdxO135P4OuZRen51UKndiBI+EfKZdBDE6ccroVu2MqrS
            UQHDmhL1Ti4hL0Zz8e6iXAaYMGBlZADqeuxZ62jcDB+Ds5Y9nONd+LliQ/qX6ojE
            ZfRM2RGaIs+9iJHT/R/bdkZCC/eTsRc4CSmSM2f3p670Kw==
            =RYRv
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAs5jHq/qH+uahPJArAPK+AzTCwSqd2ZKy6VAp/i9NwSuy
            4psFzUlRpOqenZtqvWcAX7EWHl8ztD99DoVpdoeL1QIEiVSqwo4u6j5QiSlw9+Gp
            Li0TwJoJW7VfDPbJc89azANYECAhHAt4zn/RSAL6GuMfEpBR/BOuXBml4eSg4eEw
            qHgtwg/pS4uhi5w2AEHTyY5Zu9KBaVwmxv1t1RuEXIf2q1XQMpNumiligLatMwW0
            H8QX0KPVgK9hT67s9a+eg65tzlwqyJjMdtT3F8BSL2vpOCI0K/S/fw07mPQVWmOY
            5Gd/gdi+FYiJ/UIFkhTy7Zjr/X8EnCax2sDiiReWw++32mDaXTbJe/E+TLacNaR1
            dlGGF3ElIXiTe7hNx5otl42gF/mmrwR5tNnUigrRZzoq6nrKu1y9vmmwnqe+cjpW
            mP7wlZBRwY+bQqQ8CCjHFZoNDJbiWzM5lpcvH9M8YI8b3ocwzfpP1n/KSQXFmvx5
            LygAKjbJu/isTprBVPpcYPQNyYbPrfTi1HixpUaNzZjjE/desF0FSz2cKOjKyLFv
            GfAjvJ1DbaWp7VAYQhDetYA4lSNIsusau1IQgYmP3IHdwjvo8gYEGr2tivi12CiP
            Yq7vS/w2GU01a2bn+YDt23+nyHEOZL377YN+/CL6QinUPduA1fTGJ8fJxgnmzifS
            UQEiL2mwl+I0YNHYJd+dJHJfYGQfdXexJDoMXuwuHpcAF26B28oXe3xLP1ZDZxrV
            kdzE7dnNIFiPbA+iMNy4/NeA+otZxZevfH0xSWD6HO8V7g==
            =KHJy
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JARAAiRs6LZZjZ8qvu3h3wGoOqJodRb1PTbwIm0CXjXSZx8dg
            VlMkKxWMtxV1ttKp623tayeGXqTdBzPs3I+eIGdsQASvZq3ywhkTzO9ilg2L9yJZ
            ghbU1cAI+zW9/9onmakVkfrvA8FgXwT2nZprrEa4NT60Y5EcET1Rp2BTSt48GZpW
            +LW2ztELARwJ2PFkC6h/0XNL0qQm6TE2m5X5WLkHE9kjic49c2pluuGZ2lYH45eI
            Di6/qkUi8Wo8f8fxjTMytLtwn1qQ3l8PKMnnpkXC/74m3Vc1m2/pfBzSFg3Tq0li
            kVga5yOeWajyo+Dm2/VXawr9c3U12EEvConZkXetjpsiD54Tut0opeiKbpnxvJ4L
            aeUB4hRie+sOKv4QrSw/6EMbpHON99Hc9/TSLRFBlRN1KUgejWZanfRfH7XeQEGT
            EqjbT6KWufp1xtYs334GzyLr3+4dfIZi9/bj2MoiGJ32uUR+FmoD9UWazs2I3C8s
            v6opKmrgHbxHGHxGedCBZg4smDzk+6KlymSPXb7bLuBgXkO4f8c9V6dD0S11eeEe
            nOnFweKFzwD2D9XQCRDrDFix9uEOay5+zKk5DPiv0SbNxbxA6sWD6pUoM+qDBk8d
            on2SEqGDL1C5uk9f51paB7Ij2fRmB7gMc6VRIw+N5RK7qMxCwxsTWO7SAcuaLvnS
            UQHeIIUXKc5I7MTPBaPrUvjruLXY4fwc2XynzKDUz2JbypmOXXZw4xlvjk7+CaqV
            EwXYRU1G6fTzTAXgFTbrIObwYE5VjKJ7sWbyx1tDwopaYg==
            =8KAD
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf9H6pCIQOs1a6qdpyGepelX0qPs8XFL1BmQ5gP2DRbqOQt
            rYSVufBmIN05e7wQPmKk1azNq7dFviAXl7S3swB8JRYc8dtv+WeZ0YukNCqxnmjK
            PKiOvJPifL82pXNGIzbqa7d7q1TWrmxCFONqOu/YXeWVl8u96qQy9td05Vt8YIr/
            jfu6xZNoLVh33s/a2yXcDln5UCW1MUkFCc6TUouaI1Q85RvqK6Ev6tHUJ3KJKZoP
            uQy3pS9B5Q5F8Nuq25XmDVVLH/22KOH2+qOkQgZmB6NqA8pKvk9Q6UadliZ/noQW
            1pM0ovnIacYrotRU9+81w+8h4hH9ycvp5C80p8fePtJeAUaOtXDqN2UnHlQSk0nO
            bHYyuHRX/xiQsmdafhzYihoQb7X1/DquYl2d61incp0oJpvZDYVi8IbHuAMMtUjT
            H1zWxkRHGZKYZfk36Ny4n54tMAVoi8PrPBmQ/KsTJw==
            =ZDSC
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//V/HnMr8ARMhMj4lZT1kkWyLzkZ4vVb7oOQ5Fbun6iDIr
            nrYHprzdiZovrQqfl3clRRzKmVfdqySHfPQ1xK0OTyr89C9mqzUvi/1dxo/7cfSU
            BWDr86GuNMngvS+egPl9qMD3Ym1MgeRc2zKwVGqe9JPl/JkWLyKuJkKbKpzFvuv7
            MAUbwxSsYMyaWtMI6umgUitoM6f2bDYSNn+tWUYW4/dJ9ww6+zQXYl6TlqU38djf
            Pk8/9WdQYmBCBEnQTubQhHVx1Bqij3/4Zsg7sCV3rmYhHQDF8CrSNUdCivr1m60v
            GRT04W7LwGgAEA+JQH/vKhgVxRXEiBguw4Aq4Xmhg+7jF5KIgWXKPADD4h9VX7jO
            jvdcG3daCD8Pdqco3FIGWTkdEHARmSdhzGVk8f5lkRDQwcRQGWySmcP/RPHUf9jW
            Eq9G0jrSfxbMX5DNyA+XGikXZTIQRevXWJMiMuSbiwinGAPKb+7s+7hNJxjSzBl4
            +NQfcowl8ZrtvCu41+LyVyUlaHpJNcxQuhJRIZWiMW+t8+byaJPvuZRWBXi9Y+O5
            Ws6bVkAlUD0t+xSnNcGluld9ZOOLkQFIvhNMrBq0XpIPsbrh+hnMiY+3IqbtHrC+
            RjRooyh/eq/5ytUhRe2yxqG6ydMNvdeodSh7WYUdQedZE2lcjWAreuePXQqLgifS
            XgFiNIB5VLoVcArXk9meeUCs/0AyleKpM37c23NNQYwNvCqq9Bmw6p9QUYalnWRx
            co8UUWR3vXVGFzPmw2wHs0wxXaqxJBVX9IcbxaYPdzLZeh+lYeWO4uGh9RAihso=
            =/zK+
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/+MseFWad4zqEamsc6v+KlViybfBeG9VROuES2oZv2zKAB
            EwMIk7WjPcWeyW3/7wHeDfiS8mm/8/fx02DEH4HcEYrcj61/YjJnDrrqLtACqQLA
            ZDJGQKyipECEihKx8HS02JZQkfzqCV4boNgIh1shgKyRvnqspfaVu2edANioA+25
            wtYRgh5i0FERahqQ0dprBjqBgWAvFrAtg4PuHpVqY2pRN400bvD+YwOZVNumgOH1
            OSSIJJjtS0wk0AtuvENRmnr1Z2IfZQMfJfZSZXElVNTfazrlHlVpd6U2OKRw9tz1
            CEmjsINuktX+85cb7OtVj+QDj8r1v014H4zVilc8OzZx+GF8WOB6TTMeFmUpbQIV
            WW1LdU3Rn8jtzZ/QO0RwxcS/kxSHyx2+u9RLKGZ6d9CjnNZQOUxA2CFQ9SA7fq7E
            wrXpz+VndM0ePTdoL1DgxubRxqx+SpBjiluIKjJ0Fjv6S153Vg5+SLu9d6Z0ki4e
            W6wZ0XNfK2Otc5LMxEr+takkn63Z6NxFXgnAGmUZ7ht2n5+jQHGj1ghCcFzpmbBN
            QzThzrkcicAt15ja/piMJlaErV50xN6NSlO7oYLICIyhLDIA49wxzngoT5zBgHjl
            QKx4rntwqEF5wckJOL6oP+gXVQ8960btWVFpetU4hrVP0Yhgvb6mwpPHzGEizvTS
            XgH8r1koyH1g6QIEoLsZivldDihRb89vJG60aOrJ9GCXVpSr+vgBs1E+ZYJsYDCH
            P5k9h8SHJ0RzzdUnZ59nd7qjH4EUlM7VQuHKUyFohIB9lKlXoNDVCw0dyLkIDiY=
            =rQeq
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAv3ocSdGAbaS91sMp9p6y1WOHPz9CyV7CoJ0bMZnlcn4w
            xHiE9NGASNzGh2ZhP6bqnX6J0l5gbP/XNwEVd47du7oR+w9tYNFR+g3BE/ZUT83K
            1GgBCQIQ+m5JYLisxIdIiM1QiJDjLVTGHP6G7+QFuOH4hqEZB4O5l1TXTfecnLbx
            tXmDnuyFFr3HXbRS4Y+YTM2H+IDdg7Bxh9PPETeGQldz5RYKGr4TCbyODnqGtqhd
            tI7A7aMQTbt22Q==
            =6IzS
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
