cl_bootnode_privkey: ENC[AES256_GCM,data:pLnih0aCxSlJfQa/XSPBHP+Eb9zYJmiGR8zeOmlwxYvP/hGNNi9d1BAxQ17wMOQMZMdnpbiVe0TYn1XZeygldg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:w457gcF2W0na9LsBLIpl3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:21:02Z"
    mac: ENC[AES256_GCM,data:gjbUF8i0m1GAf768uAVBHAcHLu+aA2M4+8aFoOpxnKsGc8nx3BPQG8dZY2782vm7K9H/bjU2c1D+ZKrmWAbV/onuNE+kqGBrzh+HRH33rqcsrT2ww/Eh7fIoUwtOLrVpV6daWnuKYasw8oW664vUnLnNZFgvqOyOLoNA11JQSf4=,iv:JAv2sAAyGi/50Yfrq66FvgRV6ldPPBPoyKFjrGvyaa0=,tag:y1zZkvKI7ox/lJSSHr+8BA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//RB/excXUDyB501zMWODsghAdZncMjT5WF5tkzKJjL9yY
            eY4SHg6BarcYmBumoOu9yt8/ehQYXzMpLFAkkdRq35FJ38aL3MKXuYWyMtnABtj/
            nHOsrj5eyarhkBGYr71wSBFJcaHhwHPsisirkJ6TG/jagUjsge2rcTx2SiIqRJH9
            4D4U3natQ2Moklz9uD3CVrmHfEVGBAXdHSusKSX8a1mVtFhNuvgoyrN4d6b5qSLZ
            ahNUHlr6YAfHMEPTjo4N3H+2iJHG6DS9JTHJG2UXZeTa0cTxriAk5IRIHLolgfwl
            dGQeryBVQ1mepdGABgMtLCrPd9l1eGxOUkNZWtxINGqEfx1f80gvp59hEhbXmUl8
            ntXgBWjBvKruD+oygerh+KWpPk/FcOgPaG5T1vo0WeemYZjQC/b6gHQ4hsBG1DpR
            RwV/6fnOMRw84qd9TL4mtIl5CBgE1EGphmYf60BzxGO7NfezP8vUmXlUvA5bh8Rv
            pMF8X6k9ja0lipuoR/TrzYfgCQulchYu4zu/z3mlao3wVmCJpy0C32YWRrnVujg6
            qAy9yQ94VjrurnQjmvxLubJCVWz8JUdeLBxQlacoFe0jyqS+gj6ztJozChNRIp55
            LoJKxKJY/hptnk6qlcLiwNKm57AG1pVqPFbTduXd4s5ohVSRc9EzJ24duJCL2yrS
            XgGwCdO6Jy2YLIrTGqD35lEfEn0XrsVtHJ038K/tWWzxcX7I7aQqO0stEMf7aSWB
            t/pNKwgbLaWbSXqEAeOZ8+l8Fz990i6Q9RPdTeKUe7hXBwqv3c8+mkzo2rRxe0U=
            =y+BC
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAyIkWHXbPUwm1oaDBvYTbcqOdk0iONB33eaCYME3vYLd0
            c6w8ds1nPWcsMtJFq9gxRMVuP9nLfTASiS9oYEnVDTo1aS6bJ0iuxuhVz40E9AgN
            mMe0BsvK9A01JQGVobHRDhMUGtBkgIvqhu7s8egtaGpcvBej3/bh/dC9lxtCTVMy
            aCPTPnhOAUUC9Cs3TQp+k3i5oekcSK7yvUbTZnTl8SWVL2IxVY4Si+HjEDb+haNx
            +jvwc2Vg5rnQMqdBk5yb8oayrdrhURhtr2NKyiZBbIVKLJ1QmZnbTsNPvjYkHQOI
            n00ZmrRbvZmlLG689/YXRtpGmSD2Wxe3cU1/pz6uM1TcSSbLEMeHPBz/6ONRle7G
            VcGBz9ffQx2/neeu1Hht2kpJzitsi/f2JqQhxlMZIDau1IQnjs7bm9FS0fleW8v7
            bn9OsTRZt9s5bTp4/farYAWArrTf16zJe1O0IVnjv2QaT7kCq+G9RKkk1Tdxq+lR
            /Wgxpt2UkUgrAirlju81xKtgWXRzcMmO6D1bqn3fsGi/w7b7e+3XljeVUMBWqqxj
            9JFwb+pQFFYYYvglGuZYrYhuKhwW1YG6G7GckdZNeEV9fPb0qT9Wf0u7T5MNh0Uz
            pr5KJ0bIrKptfg9HlSza4EMV8qh8e2hZQrX02AlYzslz8CUmHF8f4Sf7uno6G0bS
            UQF/nsdGT6zvD52qww8ZAeaDLJOqZb3Y3A0amjjD3xQK0w2xwF3GUyT/UpXKLALS
            4MAuYep3xEnhuz5vSyrXfe2dr8H33PEVYULubowTWxAtIg==
            =0aEw
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ/9HgDa4sc49wZ/GYvWawmOKd7hGMPKgc+XQxbI1nxL7iRe
            8AGmRWn9DqnX5mdqMexpS5T6HyXoB+FT/JGYwUuJ1ovTgsBAwUzKG8IFY6abqlJD
            lin2HGwtlxz+pQpu1rP11xjHGFn2L0pIX0Zd/lpUQWIAVON0BWuYo156qdxvpQnW
            W23MgcsZ9m4yJd5mshEPNMRTQFHuM3b1k9FczJh2ku94FYZjbbX1c5viB3t2Dl4l
            AShNcHXa3ii97tRdNzp+7ZZFboMfALnaAAykJKB4E1ZNQVczYa1URvgCosGnW1qt
            7LlPcXCPDRQ+LrwQigsQMcAoJLt0y+dnLy8lCog+/CTtv1PoxTbCY2/9X62ohF/R
            hHTWZztN7yJFLxKNS1jN8GjXKFVU5eU94Tt9VzKWqXTfJU0BqDpv8cy/mfw4CH0q
            MDxGjWjens3J4WtXpE74t+JJELWUQ/Yl4CuTTALKl5ej6lYhP5RGlrEZK7jzQTkM
            RzlVt/K0XdM0ZSuV7L4iotg8/OnW7kAgLq2Aqg9eK9VGff8CXt05y1OL/BBl6sBg
            8gWTbxgbz9i3DP77VRuZqr4DP0/Z7kNpe5pPUarR0REfAtTibToa3i+oC7+caDVG
            XmN7OrejQ7v/+M3yDK2fVYV7o7+FbQpLyzPH8ql7rFVQjv780htUK4prGMgZH7HS
            UQGxeAis8+32sVTiQscCENi03XJgXqmtHSHShvFat8pzjp42B+VpQhltDXaxra8M
            Y/rweRhGfafbj2HKwyj5B6/0fwnfcToW1oTLNYW0izrhyw==
            =mHqB
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ/+LdcVhgVuP8ffkeXX7wYoWrSzFZdETDZ2drYufw/+TIay
            N+mzLDNrCo0+9tQEK+KmNuoVannXSE/9Ct+JI5IboPnjaHOMhIM0xf+PpgZhvrXb
            5F/lcYPAb2LEN3htwInn2BryLkLCCpJq2LVcUx28lltolx0biVtK+wrv5BuYIk84
            PYAGKmDTNKL/8TqvVy8KkSl0iyVupdhNF5FNzn7tMkGcc/rR3MDccyOrnIOQUgE3
            w6jkorGZmAeKLAPRAZl94bomnEw6oO3Jv0VElHJWL3wpFqWlwEm7D3VcHfo5KCo/
            g9WzGfkXR5rRjRNbmPzgMJc94qHlbtm5m0rqR3TEVoiPjDU1lt5FO35KP+TW7uFy
            l3arNv8YMT8g9KObAFYM8GqAsyVPwhSQK78SF4Mm3xYfXz0MgC5S17bhtlgIZVeD
            tVqugmd8EkMk1dfUv35lEmZLEhoFu+2ZW7BsP/O7c1WReXrptDi6c9JYxdv3mO6X
            ZLptfDtolEHcA9Wl9YnKglLSwagkKVdhlr1LFiZQraKdJibMtXsMUAwhr56yGgUk
            4D+QPjfcoSbrFDqTRgw8MGd0dYGzdyS8WOxEu9KqPT18Ges4Dbz39bIV9fr821oC
            EcyN0ZFU4G4V+/5FMDmYrr+N2JvTLvKp92w1l9CLNhLy/hYxuUajp5hAhiXZ4kbS
            UQHs2HqXqaJU9g2tX73Mo7DqW7Sa0itLP9veEIgNWY9t8oqM6WkxRqhyLodWVUAg
            jOxT5tLsnlhMKEKk0tkijzY/4nCvD7zECLkgmuWQPkn/fw==
            =9dbV
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf/VOIx68QRFNCVtu2BTnHMf9HktIP7hxRnpfQPAedWl+Ga
            93BKIaH+Sg0wfxLO01or9xKe5AgoIRFGE2HFAG2dUacek8kT/xBZ6as5w3w6cngy
            uhVpFgZ9RTcU1tWCcEUNogxp6qDKM9LfpE5dHkMNLfE/VJW0Ml99dTHoOCJNc2Y4
            4NQzPzCzMW3AEVOykH2/7pwazLti8rLWRkand8u+q19GpHQkfdDmdd/Hjt10w7ln
            niYTmyzCVAf/hJinPof1Din+xsscshJfB6YIXD7gFvwn2sqaVYS1hqtf2DGoPfVx
            //0fKpqMdtBQjOj01e/NAnymrisox5nNg8cEzm35OtJeASPWzuC+8ck1YzduarcS
            mt/hE0V5ClpjyA0MbRMB4PiKLM8BhunoOmBTZ+nSeEdpDatbKNcZhW+HM4e1r+M/
            xjj9xF/4r/vl1h29g9AFCLLWKX0SYDc0dG+zfKBMcw==
            =vDLC
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//TbN1lqVeX/KU4OqUIaA3+RvWg/03VdIRzDzot4KErX/4
            om1k1UZ9Y88xyt1szrjOcY0b0We6iBb+slQYdPWFHMv+MCIiO3YX7L2KtD4rjedU
            HEotiz88ky+6XNuwI2IpytUd8qltcwjUVNjiGy7w2EE/Jt4ApOtuouo/jc3kSKIF
            tVSBOdEBfOjyYIaW434A/fAsDVVqgWC9wWWil0yK/oTvxMsRIDQIuXfRuoe6uWvb
            BmfTOWadPxqsnrVbsztHnoKGgPp27oCNfa0eCIWUuuzBqO8vhjuP5sMTxFAueSLB
            txEhqeVSjX+KGXIEpK4CU8JuWym0zXinGT1tpPFl8ipGYaKE1gNSdSORgVuRwLrk
            l9OmxQZWpgSbYyrFSxBnDrddxgaAwxiIOGmuy8Q2dMkRLyPE+hiko9SPrSU9wNZl
            xFpC7J/UVTChWrCHN2ryITwFhEgGhC1Z8fz2D7YUPPAWRqX3zmcI/7Ko2oqunXw3
            sKN+kWObUpdj9C2L5SX5VM3TaqLf2CzHa5Y02jY5oAf8t7wHu2qoOrWSNWX3qtkr
            j4hiewEDBdmODnAKmxhvFtzgaU8ATNKzKN0cerr+gmvpMBjMp4PQzSRFeqAdCwz5
            C+MDRlt3f8DFZKJU02k3+1D1IbnI7f12jvuKc/yOkBCiGK3JVXQ+NwX+huIisxbS
            XgETUWukFMyVHoS+y4pndBve2VuUoJY8K3xYcT6M7XjFPDXRKQuCUcIeAKPhy6ce
            9DUhyn5Njz9nLyfHSLS46nYD9s+6U+Hx25abfQAEqMdI1OL2hwBvTJ81/xuKYf8=
            =faBd
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/9Gdvs0S1BhksAH+2PzB/yuVyK4id4YK4q318H3jaqML0K
            VxMxTmAklrh5NeJigptp8dzXxOUCobO00HBmRSXwGuW7q6fv2aMNiMoQLs9mu7zm
            7+PM9l37g4P3dJBOFxVhDubmousY2rRPDrk6huWcUUVpuz7aq87EkyucRBblCGoB
            USSA1Nm72k8zDhu8vSvkRZQ+rr9XESfmb71R37SAUEvy0j5xnBm1wUWv45rajfOR
            L/0rtI4S/KgByVH0yMVuvY89BR6gq70JbKk4uYc0cvAmWnhLRfpAS0nB2B/AStb0
            d0Xer12ah0bpqVpwmwUaxRqlbGXXXcrx1OA12SyvtGTxdkxtd8eTt5k7qYQpcaEZ
            BKCiLqnxY/9c5xyo9c0xTv/kiiA3K0EaS9Vt94qn4o25d+wFBEcMDV9LyWOh4KNN
            eA3Wm39Dl+QyBeu78FYYz7FZ/r4NKJsxa+7QiJnMAIsv7So51EeNxgJ+1wg/OZwN
            3Ab74AMygujAhv9R3n2A2m2FdXnZLXo0twUkNYdX6guMJYS0bLDLc5PrpqZGw/2U
            e6ohv4Uy0Lgoj5VYY3q5Q3jrqjuE9smNahxnmSZ8fq/kKP20Ed8yYVEIIXMZgAKP
            3VdnCjj/7jmJuCYGjVJMjpq7lwvo/zgNHw6snSwWB3t3N6ybvz1HKkNg8PY7f77S
            XgE0x8BjGfOXg8s5ibkPlRtJfEk/YUZrO6l7Pxw8OT+IIRiiJeM0JF8r2gUNPMQO
            5DRzynEL3Tud7PrxsfW73z57/W/nJVYz/QjWznjJOUEF+dahz2B2ueTEkLckdMs=
            =sdrL
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAib6lxwuc8F5EgeJoenntzQ2sCryMSvxBRnpIFYj6ADgw
            22507bgmcrYb6SxYxrx+e4fk1xoZbro8pSfeaOzNDItRi/KwXwYAzy50aMEj3oFV
            1GgBCQIQ2dUd4Ked+ubVVybVjfS0+cvWNpN8LHk8obuMk5FMDMKWqQIzkq8OKFYw
            7Tg8KcDrXwYMROH0x4I+ln96LShK6XHHyi+crsrINWlDPeXMDPnOCPwxC6JdxXV1
            gWU/Z3A2KONkew==
            =ZT0p
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
