default_ethereum_client_images:
### Consensus layer clients
  lighthouse: docker.ethquokkaops.io/dh/sigp/lighthouse:latest-unstable
  lodestar: docker.ethquokkaops.io/dh/chainsafe/lodestar:v1.23.0
  nimbus: docker.ethquokkaops.io/dh/statusim/nimbus-eth2:multiarch-v24.10.0
  prysm: docker.ethquokkaops.io/gcr/prysmaticlabs/prysm/beacon-chain:latest
  prysm_validator: docker.ethquokkaops.io/gcr/prysmaticlabs/prysm/validator:latest
  teku: docker.ethquokkaops.io/dh/consensys/teku:24.10
  grandine: docker.ethquokkaops.io/dh/ethpandaops/grandine:develop
### Execution layer clients
  besu: docker.ethquokkaops.io/dh/hyperledger/besu:24.10.0
  geth: docker.ethquokkaops.io/dh/ethereum/client-go:v1.14.12
  erigon: docker.ethquokkaops.io/dh/erigontech/erigon:v2.60.10
  ethereumjs: docker.ethquokkaops.io/dh/ethpandaops/ethereumjs:master
  nethermind: docker.ethquokkaops.io/dh/nethermind/nethermind:1.29.1
  reth: docker.ethquokkaops.io/gh/paradigmxyz/reth:v1.1.2


default_tooling_images:
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:latest
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  ethstats: docker.ethquokkaops.io/dh/skylenet/ethstats-server:poa-no-geoip
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:latest
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  vector: docker.ethquokkaops.io/dh/timberio/vector:0.30.0-alpine
  nginx: docker.ethquokkaops.io/dh/nginx:alpine
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  snooper: docker.ethquokkaops.io/dh/ethpandaops/json-rpc-snoop:1.1.0
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:master
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: docker.ethquokkaops.io/dh/ethpandaops/ethereum-genesis-generator:3.4.0
  mev_boost: docker.ethquokkaops.io/dh/flashbots/mev-boost:latest
  mev_relay: docker.ethquokkaops.io/dh/flashbots/mev-boost-relay:latest
  mev_builder: docker.ethquokkaops.io/dh/flashbots/mev-builder:latest
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:latest
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/sigp/lighthouse:electra-devnet-1
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:latest