cl_bootnode_privkey: ENC[AES256_GCM,data:pLnih0aCxSlJfQa/XSPBHP+Eb9zYJmiGR8zeOmlwxYvP/hGNNi9d1BAxQ17wMOQMZMdnpbiVe0TYn1XZeygldg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:w457gcF2W0na9LsBLIpl3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:21:02Z"
    mac: ENC[AES256_GCM,data:gjbUF8i0m1GAf768uAVBHAcHLu+aA2M4+8aFoOpxnKsGc8nx3BPQG8dZY2782vm7K9H/bjU2c1D+ZKrmWAbV/onuNE+kqGBrzh+HRH33rqcsrT2ww/Eh7fIoUwtOLrVpV6daWnuKYasw8oW664vUnLnNZFgvqOyOLoNA11JQSf4=,iv:JAv2sAAyGi/50Yfrq66FvgRV6ldPPBPoyKFjrGvyaa0=,tag:y1zZkvKI7ox/lJSSHr+8BA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ/6AurBpJ5vMTtkSGA+lyppfk19EA7+fRyS5VipwUxrGM7G
            RBAKypZeO2pcRewbTik8jwsJmdAo+7X3aTPJU29SfRWTsvO7+GSCS7isSpyxnwOS
            oWcKAaXynHQ34htaIOpizLbG7QzJQmTOXBTn9TqKj4Bnqxa4MeI/Vo2lPvvYt1nM
            d4Qmdth0dVN9ytIRBxGavNpybhkXtjenTiyuuxMBwOj3KnxJPAO6gqQ5lwdVi0of
            eMx3hZbEaUzoUBm8udkSPTow1+motycRRvCMkoi8X+SAU0poTDYNpyYOwJ8EwpiO
            7ahNoZJWEegqoeWG3l80ZarT6kx4Gnpvjk6XPTma2kfLORz4tF3Crh/Jhl3cnRVU
            0KRddoPOGxepsTfYtrk3q3JFagnM6WwSnW8R+elNpLEZ780B9VWmVRKImOKkY8Zc
            mHqfBK1jN/YTRhGbz8MBKKBGKtx3PUoU9DBSFisVWmqNLjGaWtvs2TSzTwgY20mO
            hK/pAha7XkfnxBgFSCGgLsZC4PP7dNDbeQiLcC0owG4+wM72oZvcNbMKGBU5oPtM
            amE91YF/BACbgZUyviY+/b25/P7x/jmmey6wrJMr/WkRsN4HQV9MXEG26MfbrY6h
            nWGU4d+oqz6qUXfqYye2Hs6J0Xw2S/zesBy6FXyGQG44I5bFOQF02Lw5Tsb4S67S
            XgEGoykj2jrxrMBJnMyT3yLP2WCzC1cfwpglam9TiBr9YM2csBF13ZwHCCAsfsqZ
            04V6blgwBH8+oN2gG5bnh4MrPpeQwOD9kAhRTdrUIoWjqBNyzZRaE9kLS2UJxPc=
            =dpMD
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAw8QwghsGjx3a3TYLtZpnTjRIztAYz+hbbNpfPIdHDff3
            bYifvT6epmJuOxpvPgaN6Ilt7qKLBmPbtPxLIzN8fH69kz/dICIGhhOlUaa1eU75
            2nO3hNHvW0EHHcdLMhR4StG3DoQ5cviTS10eeEXcndxd/3MG7vLZHakiBKrUKnsq
            Eec0KOmm3xI4+wpBu83+pwrfq+SdqZD/iD/IKQJO6f2I5F8HnOrpfVXKvNkFHa8G
            b40FGqFd3AvZgq42bPbvbNraBx77rqgqee8Ftxk/cCTwYYkxcxfztUdV00Ml1Ewi
            eqk993zAWabZ1m2Hds1AH6VybehIiFL5TihA2dkXgwhO7WCY5SmKhqVKzOmK6KjM
            xl19SDuVEtcNN60RRbV++2oeB/Y9Z2IJiK4lLxyQOIl00NWi60Sr82dSQxDQ25fu
            Hnu/7fRCr/ySiek75FWoTmApVQliiasBCH7pyN4fnK7c9IU0feAPTWTGvNuquWQk
            Jb9vXb2p5vKofW1254mSwZWmA/PxEikE0xAjCu3CWVQ+vwKy8yEu6tVtp0RHFKTh
            wj7dWHDyWpqRGLSSUEz5OT4zp0v3qulAJJTEbDlvAH+ZhMIHkiZSWOTryEPFZmBu
            BPxScnj0HghgTdxw7MzkL1pjdY7Rw4Fpg3CYPu0BtFnfpoJc/5lViS/0vGfqc9DS
            UQED0RCXNUHCXfYGxhge0vibwXmuYqayTd1V0rkuulfTNVvSKKxxHOdF6yPHRX95
            jdqMxZadeiak9iqlWMmfQ+uDL96fsZ9Uew8Rz7LgQZQXIA==
            =ewz5
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ/+NBc1QW7E91HG/mONgRYB0WWoGGRnrFLHYhkrC2qua0O0
            9iawpdRzqVWqOekydL4ciugsDxVk802i9L4QYW9BYHpDSEjKfsu5vlJXO4d+hmT5
            ANgsrUq6VbZGKfny1ugh0YbtzBNFNeCc+cUGTUFadAf6CAag8o6ydGgMrvguUaDr
            wUnh1oqf2JW/WVcdc9WNuv1KF/nd4WSSDZjKwytADzBOOxdaQBhVfc+Co7nKZcLt
            RF3z8NsTPcyrMhqvG1aMyHMAKMVtR74X0mQQ8pI23/3H8gLuPiZqfO8KDywgtSUB
            kHXJRorxXx8o/x+4I4N2kX8xYSlA/1Kjwv3eT96zevVX4Y3SXN8oeo96K9hes5US
            fOWg5Ipypy6hyeqFZMXBgCLlj99hWjeC6Ony5xO7dnJzd38XTfmdOT4p/6i+QJvZ
            GQiy6smrRyRkDwaLfOhV/m0lWOY66pm5PRMPU1Re0z3i3RjL10C+W3L2vmxjbsVC
            TMjI32BZ5AV9tGD5NaWjZevQyRiOWPvNjJDOQ+oHhCT+jUwZ/tQuzP1Sm+bnr1OX
            cHQELq6cw95Atwmm5Rfk1ZTJyFIufkTHRVzpRzInH04bVoViK4fHcvX3suopLhLc
            +ogXk9FPzkPZk4IiG5NW5JVJjvZXfDqdeB07b9KLaQH2OevH4j+bC58+nrkGADzS
            UQFVaWeCGlXvq3ARSU7fwSsdwjXwiZVII6jxrEr8zU6uJzd1k61hfEqzUySmUELj
            WU4QU42g6nW8XxlJgNM2upcfAA4EscYLYe3WuRaG6fpmUg==
            =+5sN
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JARAAgTPTBN1zgnwxmxPjmVTMa4YMMTpdN6pwu2AN5AYbkQJv
            X4+oLgEi873XwMGNdOUhjliEu/CuEPMIDX+ub6IKaGc5J0u3yKulC9LYgerMajUM
            pu6IErAmFRm4w+mtf017aM+8GtYYRoQ7pxWnveBSlz2nRvApnlz0XtsD5UR/Ptfa
            L+atVBbDsD4fmWb7njxK8BdshgYt/6PJ6nSAjL1ojDB8RVddDtISNlhkWtFllTVd
            Ep/ZSoruKfUbb2D2JKNsJSW2Uctv7zoWZfDtfpWC69jJvZ8wm7Ac+DWjeRDtYVo0
            zLVjFej4qgh9RLphSZp4EuWP/nQjMDGKwoO56VeBz7gyUS23ZS24BiBG+2Ha5nvs
            TqT/KpljFzvTR++YrxAI4OT7ZVsX7diSYtimhJqPMy9MuyQdaBQeM5DzG/G5BZ0I
            s8w8ejFnHpAKixl7X/ZLD3+BvNaNXVG4ZcS9lIUFZnvgIRZTO8iCHLQA2kq5PgdV
            9rsh/uJEu+3YRhg9g3me7EMdhFIh8Y7bt9rLg10ifYbE+ozaRAZGR6tX3n3RLJmW
            venC3naIv33/9aa35twn2evl8AGpXTMoCSrpWxMLNVpe5okh4+EJGFjedRDxmpgg
            +igCpWZyRyHk70b4tqbOcvjMgsSZdwKxDulW+J2eNuivgUgybdUBA3iYmE2xDmjS
            UQGyZWf1WjCM7BF4mxpghbrqpJOoUhnZWzjfejvMVqDNH0tzydz1RChAo6jS3HQS
            I8a7iKftPIl5+lhpbfTCapFuerWI07Q014FV/l4GfMSgrw==
            =ZZLq
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQgAmbOeCgMNlrzezgVWADPRU8X/RGoGI5rNHRGIwnxnU6hT
            L2Iwb777l2H8/3DQ6Q9oNiCNK2Pm7PNgvhdtJHt67PjU7O9UmJ1GapCHAiorCUsG
            vox1JGIj6i1eLLcVQ5tz43x26aBtoYceTT+WvllYriGDWVWrmNzp9gi0VDyVyANE
            nwBcOwmQArwID0SBptx9rx72lNqVkZucdjcpGUFpV6QkMQtp4gJPpFOIJOxhjETg
            T1LZuvXHRxOSS/+KTDpZkM75ae4pCf48zvrbkftZh7ZPHqjjckRtyDuYwDWPp5+f
            YZEdHzkKOx+T7qDxdXe91rr7H9ZwI9LCkuN9Ch9iANJeAYCvqswmyV1rtkvj8m6z
            Mi+1Mk+jI8qpI86UUmiHpcAr2VqtrzvIIL1tE31XjGZejC/F5ibG82uFAd0l/tGC
            7F0z+i6XShqKhO/Jw48cnRWjXiHy0z3oe5p+Ow6pAw==
            =vGGs
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/+P2OIYnneCtpuxEFUAqOWmq/NYtVTa5GUXAi7p3AKKhBC
            /oc3jiDBsUF88TbfKvosDjb38gBK4+eNplBZ9jqaHJXxKCw9KSQLcVPQtQTCgg2T
            t6mKmMzHGejIK/0dISWifHq2/HC7beZ/tPl6zjKPCIk+ONrljPP1RrYLmuU+oWHp
            Ofb3MG2+ACKBMxCf2GwT7SZmNsH4OXok/mfQZ67BBmeCTl+rgnqxjUBOz33B4ktW
            MZtGEcHfpfpepbotemwSpZ7lbP9VYh2h7PQhhXMprnj8MwAQuS8nUagNFkV+YhHA
            659UMaCv4fT4PHnolKVJBU9uXSUNIKE/bdvD9uoN7ItbqRXsSLklpbber5KyRXcy
            U6/AA3QuWzYFF1o9YxnATY5W2J5447uAe4ddfo6WU0Z5MNIcIDgGfkfrzczLlwG1
            ykMzDDAv3X0kR/0xIXf48EMLQ2dEMbf1xGwBsS7YzWrIS5OObLwrQCVs9wpGDk79
            sG1QKgcyKaq2L6MzXZezFhyCX7cfbPlx1XMdU3YU+ryaFTUKUCsNNqVlE/WSUPS2
            YQPtzDyH00ODPy5qZ085zuCiGu9aBiAsrZ0YGqfQKX9hVEJwBTZEZaFtY9zC+1ux
            mMHChhyNdsvIykLWWmLszXWXhHUam1eToG3FDpZzY+tisE62CA04HpNsG1wGQXzS
            XgGmI8JgVEpN1mBHBcN5PXmDasyASBip3zJ2+9l/CQ+qRVIAYsKZ3oc+oL/fFGZi
            o6ruuoEXUBv4WpYiiPDm5CxeoVxLBW6XrPXJndZogReAKuWtccqqVsqq9RvciMQ=
            =WKq3
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/7Bb1f80S/VmArLz/wvK9r1X8PBuuTT6xctzqYAHH2utfU
            kI1IpI8XqoiwaE4esHnOgIIGjRbV5n1uDqWqBwKYR+JQmrAJRwUsbMy2L8rlRn1d
            uaIClyVbF6j9RL/30XdiLLhhwgNangGGDUpo9X73c5GKBG/M/g2ahW6BXsjZN+4v
            ZhcpezOKZ7VcCYAaZrZYAMYfHfjiqdIkMQPmeEBguPtRBMNZ8+pLRWUXmQ1wQQi5
            /xdy4vebFxMOYTJAhOz8xDVx5gLHhN0QSnjo6/IUcqwN3XFBaeo1nR2iO0exA+Yh
            h9kcFuA/hq6LziNXHYvf6alrAWscng1L+vEG/QSdPbAoY4zB4nB9QtarGdqrLBx6
            Kv/0Votgptx2EwCOzAXP//O7G+2WvCqDUtVoNzlnMeseBIP0j4z8RZ7h1yruxucD
            o4fWxLF7/EPBJ+UkhTv8ZJ0Hlaetas6wu+M7HxKRAuuBIrGSTIjzrYCcjAyTaQCd
            Yek1CG7iejEy2Wm3L34jtX+ujF4KHSwMv6NxWTSAobH2Xu3yIV4vWG7q5qu9H3W8
            WIs1QBwyJSDuoOmbm2oKUSE4C+3XkBLupOX/DuvTvrDiszNef25AO5S7zSLvJrDo
            rOGm1vPoCPa385SOE7ZOA1ixPYXWgGgAr/nSgDPEE7BKqvllP+Vs+RjpDAhEa/7S
            XgFVpT+PS8NRwhnL6D6Oep9hmJONzQlXttgbr66vS29+IZQpqKdSNS+Malk5dMme
            jTqXFrGVO3LzG+qxvyiIz8jzzpI4XG4pky9EKVjaFo14KeFS24QABknUMsUiGYw=
            =T9K7
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAT9XKV+UXZBI7lPqLAg4RYbUG+4xQDv+tRL0/OFYhbBEw
            sRXDU/vN/UAKetqzgND2TGCoAd5e9UZJ09HNbJgdPhErRIVNVtsdspW7z92mihWz
            1GgBCQIQaYTvviyLc599MA0pN+7L7wEtcWKrrVs+Z8jUb2rIbnPeyDfQHK1hLBBx
            7/OCXlo1zpXX2t16MhlNPgGh6tm8WZ1sXaJ6YRluoqbQqisMELhxUMntUmqViE2J
            B3DIEsftbYM4IQ==
            =wD1+
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
