cl_bootnode_privkey: ENC[AES256_GCM,data:pLnih0aCxSlJfQa/XSPBHP+Eb9zYJmiGR8zeOmlwxYvP/hGNNi9d1BAxQ17wMOQMZMdnpbiVe0TYn1XZeygldg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:w457gcF2W0na9LsBLIpl3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:21:02Z"
    mac: ENC[AES256_GCM,data:gjbUF8i0m1GAf768uAVBHAcHLu+aA2M4+8aFoOpxnKsGc8nx3BPQG8dZY2782vm7K9H/bjU2c1D+ZKrmWAbV/onuNE+kqGBrzh+HRH33rqcsrT2ww/Eh7fIoUwtOLrVpV6daWnuKYasw8oW664vUnLnNZFgvqOyOLoNA11JQSf4=,iv:JAv2sAAyGi/50Yfrq66FvgRV6ldPPBPoyKFjrGvyaa0=,tag:y1zZkvKI7ox/lJSSHr+8BA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ/8D741dd253TVL89PtfiFf5UQSsUtY8a9SLBbjeKt8wd+p
            PGIA02/mNLLOP29bNHwBTYqZhbweIC0OR3lHBhf5hVI5eanwS84zD7CoQ9lnBO8Q
            MJmKZWs0iUZzKHcSiH4BaQRsx0GP8o1oFO+o9YdbbS5xRI/NmYeVfoqXzWjBde07
            V4Io7h4xzcbXvJtSO2Dfv8bVWYGTof1VOq+oOrPswgwBgADWuWinlnTeGP7heGSv
            A7cF6sYuHArq0OWZui14wb805L0yjEHhZLU0zkGjq4JvYF8ADAj7kJHRoOviJZcB
            +Yrd8DtrM0Wq3p6QXqkVAJRvJlW+SiUxQXhsfiM7UEYtiD0GPqnRgsro/5qbFWGE
            96vrOCis3WgXgAa/XvlODhWW/MMRD46DExgRlY8W2skzaOv+3uytUSz0sBAhHovk
            ubwBBhtqxG3jzsKlL9a2BoUjuZXZJDVxGisAPFtoQF8BK9AHvoZ8hP+yRkq3FIaT
            RnVLMBLbY4U5NwWhdDMzgkqHL4h0SbcPW53kRq8OgugCjE2RNrYllCBPIFVzfctU
            edRclhzpsozBj9VSnuftzsegL8R9YFvjf2hEQT8IruOayxFgqBBCIDlfnNXbPBlR
            X3xXA3U6ROU2Mv/LeWDeP7p3m1qnIYm4dS5FK3dF30qVf8qQUyj3/Y/yuLx/VXTS
            XgG2ANwoQ0h9GBLl5ro73Xyll2SRJbln60n2YS1Pygrtr5Sal4BAc/O3c+pJe8KL
            2s+Y/a49+aRzGm9rXFJvimcSmg9ZX93jKgvQSQX3/mVUIyuoOBo2YryC3olcOTo=
            =InZC
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGAQ//UBRXQsOLeLwH9RFRoLmdVSNzIJ+PREGV02BDd1ibcI/t
            P31NMTRLQA0pp47QdET3YesG/1k6pIC3yBaPBkJWsUH2yoEDESDtArH+dhVcGFPw
            nhgcItIEtos5Q4QvjpXYdwpp8RrUspZdrfh1RpiswvgPMMxmef7zp/rDLbltT9d8
            kWEx+PoyH09FDbaCcdigETsqOlu/Da3UNWrau8nnlNyE+HZwUujwLx2qt2B4Hnug
            7fK3oB0yqpcQ/Z8qULlsaR6B89ZxniJNbu7Oi5yeI4eYKwjhdfoCh3+BpTJa/v6n
            ONEXheyRaVQdjYHzwIRn/pmA85cQpS6IjBj4UceicVEfEbuCSLTEFijc/epah4oS
            jsq7qb2iuU/r8bWblSMvnz8vzzC5AO7lkVSU2N2rnVcll5xESCJ5riRXw9RR64pZ
            xikoOY7AGYLaJiT0uWgoiD6ZGsIXVpBjv/3c3XeMwEz+o7qHEihl/wNjNiJwS6Mu
            5BV7TlTFVQrZq7egv165lj9bDa7HqHVExw/miDOLLKqnswqL4Op4EdRS3N7sgvZC
            4B1wfv1LvGAIpcLBMwxGuLScg1l3s0jAmTS973I3l0WyMd2SBgIB0q+euvYZhCpP
            G5uKGG0KI41no0zZzi9HVmXyH2y9z+/i5QIv7vSTY8x8QpauWAL3HqI8bjjon6bS
            UQE9QG78iPdz8ZaYpHl8ts/LwItIdXKvW8SVI/nk91wloa83qhQbWzNw/5n2dqjb
            qT7+ly45D619UbWaLjqwtub1/inM66TcTdSx/01TNnGDYQ==
            =Abas
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAvpXTqRaN252+LpezgIfU/UoJGfVa1wi0F4vs//oQlw0A
            l2tOKuaSZu35IuTltyNcLXd8tHbAMuMq/XWj6wu5MlR5+YOTCkgp5mJ2nM/YNPCC
            ThZwSruRS3ZVpvlryGYLb/9SzXu1hqfpdPQ+8kjR4bWBkCpvzDNnvzO081b/rb8D
            e1p28L5Dqzl3O88dgUIvS/REXPq7X7LDojmxbqyflM9PYyKXSy8PGJ0aIuTLzJvE
            1xaYUGPMMHgIW6oujFUaVCSDK8TE91BU7NJH3+o3aUmXKksdD6VJDAiH7jnM7hfs
            lkxU/y+eORJi1f6skB9649qVVhFlmjba6S3tIAcqBiH9oTaRsev3/hRZ5ZJMmaBZ
            u4iUkQoD0SdlcV4SL3hbrEatrmR3YQZORWf9T+YOhJtXzvZvMWObCMVAy8fRTI6+
            8MC3uun/4+MrrS0EKzkDqifuht9NLp1WM5FlzLv+CQCqvz65yhDTmHvVnt02jenh
            n0J0FlD7+hpP2pCXR74NN5TscWKAfda3x2yl8kfVMoAQe5Gfyyan4kWC18bxo49W
            +T/ceTDcfpDJJIX7nEvS3ARJMkM3CgBSlvILD6EzTO1kZU3GO00X0lMtXJeperrd
            V6uEKIF2Qa6dibx9YCdeeCC1NbxtikL3EXv+Fijd0N3Vi0g4O0gQh3H9/G86sjjS
            UQG7Gm6VzXjdDM4m4Bif2UZ/g7MiHmrtp9FOIwnTeVgKL0aKRjoJ9BMOoY9k9Jrm
            XrRbcA2FHXdLSwSlozwMzqRa+Ww+vngF1jyVUPt8nOi8uw==
            =Qcx9
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JARAAvGUY3ELdGU7ZJOJ+3u5GSf3TFqa6oXjPOoK2KvFhIUDn
            FjfPVWOIpUTZQ7rp2TVYjTixxB5pSmA+jFbJN25L+qjcbgNqWkW+JsQXPua37ziq
            l+oW9PfK3DmBSFBp73SVpiw1WKzsSfexZHE6M8aBBqz5q7uo4CxEIIJBD0lVEKuL
            64vFzq9tFLvP6CpKckk873EbYiRJYFmvpXH8isZHdpjS9AJK1Y+BGtVIKXmy3FtY
            XP+tuCxD/zrGJqYsC3BQG3w5m85kRcZya3gmdpjRw9abRzoCQ5At216WSAjMgJeL
            BT4Ngm82vWkc4ZQzZjptZC51sdzzbkDJNFXwFLmgNbrxCuBrm7FSQTA6jnieKrAO
            BsrehFYvbyMhS69yH2/7KKMmFe709mxHdniSRqmsilQXDzOgh4HYsfBPCEG+Osgf
            Gc1IxQSuNVGJWqp8osHIllgancMVrmhri5GigpHcilSapIflKtOrRfQ99O1gGIgC
            l5c3BvauVQc1QHb3nP02HAKiz/8irsHryQe0Q2ivcy7VgtlWpmy06tgRoMe0ifuc
            4ty4Hx264waj+FH6Xwt0xTf5CetBKB6NPhwEF3K2mcRhBRCs7K6gvItzLIRykRDm
            WmPKvcaP1TvkQVHONRYG2A3mKrdJW5cn90OHnt8EUUjXB5pBD+4t5q/g8mPHk4HS
            UQGswpu428saV1b0H7pIJI47/FR/RFU6gUDJvPUJG0+pVLBkitl3mPzw1RwpTJzF
            Q//aOWxMPvQKK6asO7eZZidc7TrYrEyuPOLc/QRiY343sw==
            =Bt+6
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf9GixYDMpEps89Xp/p7rbzT9Ebfbo0bi28P+8UHG96a4Sr
            A8fF+PN4ugpgY6hpaE+ZJylgcHmJ2i52haK74HpwjtHK4tC0k2WziH+FdiPtDs1b
            st14qVV7Qs8+5/6E6dzDpxKE3oc72vz14bh/DO0KN3bsht8u0JCeMU4FdV3yfHaj
            QSd1rQ/jrt2n+g9f6yAySmTfzwIhz/+yJ37wPAIAuR5bDwEWA9vbDv7MbBv6EtWJ
            zoQmIXd01sO2NJlf2V27zYUxgEDWGfBW9CQB0l2y9h4n/stkDYNVIpyadxOyFdrC
            S2C6EzVtIOxNAXlKIOPoASJqQmeDDPmMl8XJtPHoy9JeATkxunmhvPSaGERJ59iv
            T52F0o42qKZ9Pe8hYk+mJvDZHKGDum8bWzgjPFQs0qmUwDClryr80A23TmtxVWKx
            U14zNqClIaIkb/lAAjv/XoSjEHL0ndREbLTa3IxQDw==
            =M/+O
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppARAAjbVDAXMU06Ij4c5Q+149lrYD/SIi6cewNkHmWo6vdrs5
            kmlsT6RRnrY2jhSYjRf1PTjdDA485koVM2aStIzpV/tajfwOUQAyC7PjHcPIrxJR
            vggGVXiUznlD1RCOv7j1t7K3jbQ9YjdV4eFzwvu9xFZZBKw6ihOt6vBicg16l1T9
            /fLoAtsLJKMocxGz/GtVoZ5QdDvQTpc/k3HO42pCHd0W+qQhNZVKkZ+wqXAhcDKB
            2EWY7TVQQ2TRzRkTRMb6969Y+betNsB/hZ3gbPxzlLlcUerAIkJqZA65Gf1fGolM
            WxycA6JKpBMOx2d3XidmaxXRH8PpfT3IA1kLNhxPuBi8p8kySP6V5bNGk29fbCk/
            qyBy+LqZxw9FsrYRWcQbwmI9FpJgYx42TQdLFy6Lj3P/IZbD8Y3wXt9DTKfPI34/
            hA1eSm7FTWchhDPr6ERHFbLqWdh7As6GpU9HNkmBuIB+tKWrSAUFZSoR/NOGS9AS
            mAwWYOlLBXmSRzI6wffvANkeYT+u/Uq/TIdk+iZyGgORkVJH0QREkNf+V7cSU+Vy
            fKHsN0kmdfwXnFUtZXF/i2//OUdQWdjQ1k7m4Qr2AjKodynZN9Ms2QsJjzZTuvoq
            RJbmNpwf8Kr37kzNxU0usRPbut2UR96OIK/32fJgqagEH301A+eb2BuBNl+yYtHS
            XgF9ruMBc1cPKjCxOqPK43C0j++NdlDhnY4JEcp8SUIZZldBRlfohfDP5cAqQqdI
            MIU1KYLaD/krLRVyq3z+HUCBmd3DcxKK7pMTLKk+y1Xk0PlwXGgQjDXMDmhqR9M=
            =Y4AD
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ//Zqv9+RRZZWS92ewO2eYhKidH0UWlvccgokOQf048TYyW
            VdnCVGlFR7cMy1K7sCCTjrG0aEBoD4WdXIzbmZFN85pWydxHq+9o+A9L7NHDLaor
            p8Dh6tVNkeLvldFk7aXb1LkFJcwIk3zKtDE0w7yUoVQS09Rc1AFGg/DYeGwCZrn7
            Kz8izRlASfJwopS5cLwVqq6vrxi/Hzsefb1GfcUA3eViCJ9LZY+ymgkFfsWk0hW1
            Mcu/g290WrMmAjP6mLpwXhIMVy8trdBO4l6WLuSgq0AJAiwTdb960EC3yzXYjpx0
            4VCfIgu6oKHdaYh8Azpy0MbuzCphFTIlgnn9pvpqk5YNlicReLmQvx/RBAz/SvFd
            x9zRfWqVtOv4Mj7YwV7NUtUEJeqhgFzdOai2jF7w3TQl+cxJ8lAdlz/MqA2r34QN
            byv8M/QyVHFY0KPQwFs8SdmFLQScaE9PQ2luRSQ99CaFGwd298eCedJlLQb/GCQl
            AVkFRfCulfLiRqfizor1q+kDg+JyhFTZZfbU/OqDtVLmnDjHOvidrucM0V2zAb1w
            jyzBa81hMbZ6NwkXRWXEyfM1SLa8VNXLU/W0VdvKKL9KGO8UeXu0/5SzLhc38zdx
            cTkXfIMXsR8jSgk1tcpM/HNpxYaP613xLhQs/a6PcUk+Y9HFXbWXTEyOlVMwU8TS
            XgHILqQEj4ArpIcqyrsZJnJo7mdgSKRe0SjebvIlf/cRq/Zuj+Qq/TVLz5uXnCBp
            Cun84EnxlWi/zxbEyaWTG92dLLzDzEr1llXRmw8QX23gGweUFc++j6JigAv2DpA=
            =NIVj
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAwj/qE2egclLN9ViKZXsTG75yfM5vk/hzznvJ6SDhKVEw
            DSPLnPtTCEcUvkKG4kIjk2EHM2jtaaDC3YcEeAH7FSAp9o9N+3gDan/YeMqTkkru
            1GgBCQIQvcFUoE71cg9qeVnSVG4QLDbPyb36kpMfFSwDk09FyxvO8qRq13nRzCG7
            ipucG4Y2e8RY5QqUAwXCStpgL4zTiuXa7vuYVKsltxM/aYQs2Hq2VDZKV9I2qwYF
            U1j+XrkhRLLtNg==
            =c3+R
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
