cl_bootnode_privkey: ENC[AES256_GCM,data:pLnih0aCxSlJfQa/XSPBHP+Eb9zYJmiGR8zeOmlwxYvP/hGNNi9d1BAxQ17wMOQMZMdnpbiVe0TYn1XZeygldg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:w457gcF2W0na9LsBLIpl3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:21:02Z"
    mac: ENC[AES256_GCM,data:gjbUF8i0m1GAf768uAVBHAcHLu+aA2M4+8aFoOpxnKsGc8nx3BPQG8dZY2782vm7K9H/bjU2c1D+ZKrmWAbV/onuNE+kqGBrzh+HRH33rqcsrT2ww/Eh7fIoUwtOLrVpV6daWnuKYasw8oW664vUnLnNZFgvqOyOLoNA11JQSf4=,iv:JAv2sAAyGi/50Yfrq66FvgRV6ldPPBPoyKFjrGvyaa0=,tag:y1zZkvKI7ox/lJSSHr+8BA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//f3LADq0xDDdl/gx2wCmUUEiGSP+wFUNjwo838bx1SBxy
            3jEzwVl7IjFf53/81PcFEKoxi9rNhWHRVw9xXlPmGbtpxTOMIJQYmQd1v4Eoffp9
            gahY58HCuk5vBTbA98uaaobY4g4jVMKaF+eaI099IdjEKV5DNmvyvvnmdsQUpL3o
            NLab7Cx/xwFKM48XagscbFpvnml5UMZ0nfqO8xAkF2B2TIK6H8yl4ZoUIUlJu2Jb
            xX9rJiBb9sx/5yLeo/R3WRHF5i9eDMYmsoaS7E4bK7y3Uawzfvwwn8HUBQqMdCCz
            RFO3fHTcqdbvNlKr00rdIdqE+zz+JYbzg7sdwfknqB703jFgEtOTp/whpNH47mY/
            +eqPACym0rgVgHdCFJeogSa7pKfbDRhp5mLTMhw0+yyteHoaOAG6EgW3VXj4pbEJ
            Oo+gg3icGI1wiRP/ANfOhSmgRpNzlLOT7vRqPVG4txmwp0QkzS9K/zPvIZcmCP/g
            0W/EuZxRcBn1+4O4VvYBlIPdg4KX9Fo47+gOj2xlgsMF/xNPCw1Q1ejuCIszhY7E
            MPQAh06Ap4Q7mWTtejsiLyNTMALDMHY2Q7gB+NGKNVhnNVwgJL/xxBuYUugrgENC
            fqKcbaVsbjuUce35NSGqnYqjJ6aX/1C6558NhpmGAWizkJq6OqhOmWEGMnHre2fS
            XgGhdPegErDGfPPrejvJtOhnlZXACd4Qu8LS18HczKPgk6tNoV5rUEbR+aeODAxf
            1vB6QZmkQnFE69P1WmEokV3hr1bGaNQy30nCSQdI9FuYDyIqeUmJOBkqAJ/NyF8=
            =PC94
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGAQ/9GwZahQo10G+YtQg2rFZ4Mu+6VNWM3QR64ScKAwCrIsjO
            YU9fRbeSMRf0yYZs0C/qMA72Ju3b964/q3lKbnzaVN14HqwJGZaHoH6IG3OpCZeJ
            9rN2We6dxEOwcwDX/t7+n0VjZ8rMeff5yr+z+VVQE8oogsMuv2XIiZI5AoaNLADh
            X8bHfpdPt5z1BUjBkFHwwxeHNAwtr7w3Y69viuh+VYzPoIMK1P+M+eA49OEIbIYL
            6b4wQDbee8eRBI4OIi9KqiLUyjEfU+WQkBu2uz7+dAQSt+stWyfldd8plkOQmoqO
            HpT8tiQ9Cphy6JKoQwNdA/rpvlkedpUGx/sdD6pvp7vDXQzxxIFmao9mg+kxZbKE
            5FA41FJT0Bec07SsW9qKRdWL7sjgPf2WHk5U6GiRK3zZQ+ngCElJAgY2iKHQLQrI
            CEFDHRFObU83mOYdS8EYDozhkSnwkTWF6r2reYdZQKDHd1gSbJKVmReL/3rJZIvB
            BXeX4L2SjTA+m+2P62MLj5UAGPvD4NHhQFfAN56RVwAjIP2lCAyL1hDQtoj+91i0
            t6EotMaKFB3wKurUq1rXaMuW+FXIzf5uL4Zx8he7H4rxlAbTrCHr+cHdMm0blv4H
            yevCX7XpUXqjo4GgQr0zyQ/Uqnz6Rr+/GhE2WsASY0YNBoGahPn3XHIx5et9GeDS
            UQGCcfBvGeBQdSMEEI7BvYgVgfVriRLNMSDMosoDBG0t0TGOpRSI/LKJSkJwSsof
            RmE+RTGPeowMNhsrEfKco8rLZXaqgrIr4t5ic7GKp3evMA==
            =lFns
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAlIUt8YdKmYAtto32m/y6OOp7KtA2vmYW2+VKs+HMkeTD
            Gr2kVWC3PghZmMZGvHLZ8+l05N42bj6PkQSZqtPWZzgIzUFmWRTCXDbnWhZii1OP
            Fcpbev7zjJSZXpfpFxXFSU1YUK3kzEE4e7LtZ6lLuv6eUs92e/G3O5tgSYo8kXMf
            QL4sGglovIGUmIK59gwR6RD5BtELMCsX9NkVE/vMN6oyjwghbAS0v3swRiRxoXG1
            r/m5v0DX+R0B2zDZaX4emusOl+hngVyJtEttHirqflMv2xZ6TygqEGaGgAFEqw5K
            V8HfRZpeEfrs50AeEYAx67a0bbnf9PXEAnMvh7FXODeEVYauymTtL1fbNxmGQOUY
            c08Dd0z47bz9Q6CF9B0rHmqAHDh6S9mLE+V/LLqwSw4iDzSyIys7W3iJfpFCSkI7
            mAHRcfdPYr56pfxSmIC75viNgNoDAveGAdNCoUOKQDGDsF8PZBezTWfsNU4GRnSE
            ffYwLOrYA4F+WP0x2Xf6a7GV1v4A960V/r2jWcFyr0r1m73ug+Ip/s9+p15yDVjZ
            B5QOiGfYoFe6aMjtojNZFWUmgd2Vvpeh8nPa2yGqtXY8QMEjRzgm8CdQe85v9IuB
            NLYfgfAvYGek0coFvwuDFUNrYDWtr8+1re89FVUlcujxLDqCOsxKI1ZtD9VQcbfS
            UQGe0MV8iaPrmkc4NbdoY699dF4I66nKKPy6JEG/c58cJvg61sqkp+V5oafTnRG1
            ENhLStXnFdrLrEcS+IFDATGqp1rVo3bDzEjoj2iIL7qgwA==
            =/15a
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ//Q4GQgc5ZGUP2naM57SBzR6lNlQ/G67i8ucRs2VjdY2H8
            6iIMQdrM6pGfuf3SPUmVz5vBkRvy04ikwjGN9IhlFJWrY3DWUMQ2CRZiyepAbvFd
            EspUebP9XpEKML/Um1c4CGoKhbBQLdFRFk7jRiBNwSQk5/CpE98Q29lKibiqN5f6
            v30EnvEQ56eMD+WGMIesQrqC7lcL5KyGVkWOWmW6h0hgegNHD+HpFv5guzyV1Y+v
            tenCLOEBSTOnRoR35HUe/6Wux5dADVjRvYDE3oP4wqFtRMMBNmR+tcN69bnnvkhN
            earjpmEieN+5m8FMceuBsFhmzXINJWsKrA+Dixy5uc1qcebndPO8Nx1aSu8gr1+w
            6Mr2PdZHtUFeKF7IL76AohdJZ5gIums1yOcs32THa1nH7PRhiQFXFfN9lsw8KRI0
            bBNp3r+HN3p9aoWJl0W4KQLlRxqN6kbffSff2HozwQ/YCG7jRoRd99LloX4Up3Gt
            rznHnuoJJ5rpYVo+v1W+YvrRSlbRtdsp8fPHyH9LgkhPWXf0VUF6Iv0cS0jq4Z+P
            KYUSpY+hV33BO8dU0qlGQOPF4qvU3ZMNHn+rvHFPCfC0WtMIKNHdb9WoaiCvBmIL
            S1JAcIE8QGfgKWKfEtGo0KnzbPtFvGRp3BZ11z/bZUPWlgp7jdsvdaaM3hxDDm3S
            UQHDlhwNP3y+/b2RS79dm9Od9HjVFxCXvzuj7SS2ZV9ehTaGaJdqNf0FYGK/MXUM
            RXBhTZu5pAId93joo6M2KYx5/MQTsND+xg/N1bQn7cjeEg==
            =8gu1
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf/ZUCRAl/XAumeeXyle+aWMgv7ImAzMs19bZomkFdhfrRN
            xGmJTEsTND0IbFHZD++PaOQj9jhJneJ40bply/cmDHYBdUWq2UVUgn0KAVr/8IST
            RaXN4IOMOWzXWlbUtI8ViBdwhTLslFiYhPvdzvD0gkSuHAyyHCOzLgT/0paGdtA5
            SxeocWTCKzSWg9W+cENsuI44tmh8d58lUN6ktJ7qLnU4NykIcIJ+WffVezuq/qYS
            GN1KYu5Z5jZdaKxWiyWQnZUCzOvCUPIUacOoeah6tzSbZx/VMCyc2Z/YVLHWfdzb
            CJxRoA5T5tfSXtrHBiIiMTOyUshcI68rQ8ODET3oWdJeAStIgpHRUhlFTv69vB0A
            u5RdHLlQvcVNCTiT9oudoZQOEdAXE7vcv09UImtuTO/0OPZJzlnTK1d5imTmTBXD
            c2b1UKGUmlgG8tqeMACnUkkycGsXHKFe91wQIjJIXA==
            =v672
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/+KygLN9+jSiLBtEP3wl3twyL0wV9hQo/HbB4f+VUfrS0T
            671LQ/sEpg3zeUSjfdTQUYB8RknoX/n8cvC3IVGb/nkAAfNkjPAGsbcyrZthQwI5
            6s7Y+XoCo0tT7z7w9B4ccqDF7LoCA/1aIR50i6kphBMxaLf782qCaeX0jrXbFsn9
            MjxGDE8B2B/Afr5KVheA+okZJ6q4fER/G/4nf+2rqzEa7pO7ld6PgDcmXzapytcY
            P6tNJJvy4EvzzNxGrZ7OpSrv+bNyX+4jtf+TkZ6BCuNXsCObvTqUY3Ujzp33EotQ
            AltC/L7jx6eY5xWCphTx/c3VNYovVG68kx4F49kJStUvQ5b1OLvmOheRbFMo/I/D
            R4O/Brii3bChfJIguXPkPOnTj+q7IJHlIlPhErRthaF+gf0T+iK0djeMCazA5CmO
            4NVWfZiEQuQqJ5YVhEZG8zZklIkYRN3ZLegCiYnVaMl/xFHCoeJ0k4Q5M7+chd7N
            HIlt4qAb1fFpD737cJqZkvuFjDyHJ9cKh6uUhRbzWL8f/qIj1XUjAC9LoTn5FNHR
            Geuz3vR1CnefiP9M/RwWBknEB8lmu4Jgx4xDr/AMzQphcE9dC/oC1vELFnwq5LeP
            YhL17oi3ii63P5Enw7gQDFOur0YJnnMt4jNXMblpBHfNnXddjoibssNihU1z5drS
            XgH+OceCX9OYwpokjK0RKj/ZXLZCyvd5nXjKhpZs4b0+Hr/rneJcm5Sc11MQP6oA
            bcdFa0eLG5ym5sFFQJx/Slo68R9xM2+PwaI0ST2+SWB7vUbYLRt935q9eTMrJ5w=
            =AMDR
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/+LZRoPfh1NL4PXAqmWl0ZRS6XWjpyrjY5MtD/OTe/at0I
            DEEnJ2cmWVWcy1tB86L52A8MBSkIfvpZOrtW6Tyk0ByCNsug/sZNfTVhgbVCRVjp
            Gt7pBjjIB9W7DufKy27ZJDuEz954k3GSL5gNNcn1Ng3BiXODrj4dYm2twvEIPQhX
            mczY4lNDFRBislvjBud4keNnyP9mt5W9qHMk+oKGtW/g66z0wy3pT4NxmSBDM8CZ
            yE6bB8NjHVssjt+kH34KzilM6BX2K3s6yqhdwf0lNn99c8rPXvl2WsbCS99Kc6I6
            jKKOAccQOD76P8UWjsY+MnvOXRLNq8saSVI/2NuKFfKbfF+lJuS0RA0+vkO24FJK
            56xsal4XBVJcHfcHh5sCDYk6cxlv9pvubIg7ezSAjEGbWzntu4Hi2D3JxlKwS/Ut
            gccwBgS+IfPm5bMWfyVtMWDuxKB7rYdP32yz9RFb9wck8ksURiv/oM0Z2xo16v1o
            0o4XrkACoSJY6U4CJ0cn7bLv6fOesqrl6S4oG6BED6qfMhte6W0MZAl/qLfz+FIx
            4ebnGpEsH78nHrncvHzlwrABmFX/pYdkhaoEBbSkqBP6/GegwJWp3yadhX25I2QW
            25B53cGpG+6cwKJL9uOV4qJIyr8f3S8k19guN0GGfAu8G3A6AILxV0fSKrl5xaDS
            XgFjhJuy9zrZC3XOf8uPilM2CqMQ1SWwqk8myXkx8nxHyXAIbT4+ufy8KN39ZbGS
            S6Iotd0j0WoPz7VAg5q2v137JGECnJinPELHN165FQiR0h6TbWnCf1emzfsp+tQ=
            =exMH
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAAvuhGDshjrRXYEd0IwwhXMgDngPP4I/gsdRAdRUh1Wcw
            Pg5TN7vzLKYmh+XHEq5B7T2rHNsQ+sPFcjVfyr9Z82tffw30Iji/aTdnmoY/4h78
            1GgBCQIQvzi+38M/52Nnwbs2wF80J2i2ZR/hgZbljoeu1FKhmchKrerAsiLESIcM
            VjtdtESYZjEvMn7vxbcnguKwQUbdV4eLQ6d1B3RZygo37VFtLdkB5aGUmncua7m8
            KCgBdywwHs/5TQ==
            =nnlA
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
