cl_bootnode_privkey: ENC[AES256_GCM,data:ywhGk8vFMF6ishOKGWMfSn0IxJttDiSBqaHgserxIamQvRMzJPcmMvAStVfMZB7XBHGyiWLy9vvDFhhQzBiocg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:d2jUPi/+szwu4fkG1UuYKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:18:36Z"
    mac: ENC[AES256_GCM,data:OvHF2KM4DeBqRrBC2bhcpCrUbW2mwIvt+6+nwXld/qoDhgTxT8DBXGAfFY9wE172uElnV6O2bHGfgwCVX121Jg6d1rYzvcXrXuLaaTqLCTjy3xAkE0GrjJpXDAzhghsY95NU+n3u5Rz+49SffK/sR/dqRyNsASsW64eTzdMvXng=,iv:5di/nwLQieMrIxn6IEOP1UcJjick+X1l0kLka2e/72w=,tag:7jfPRLfWT2WiwllOfvxtEA==,type:str]
    pgp:
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//Rk83TnYlhpX6GfvURmwSgWwI3jPgMQWv6/7Z37d4f8dq
            ZeVX1Jd/SmDz4+ATGNPcUJBorsLQq3fPYYTife5r1Ye6p3a+nAJwMPiE2yOSoi2+
            6Rg0Oy1p02cxkUudz1b4CmSQjncaBFHnPj/cEmWGTQUYFkPDzsOJTRPcK/t93wAU
            fIbJnuKI6UUHmsXO775RixBoIUIGNbsy0O1nIBnuVQW5dbNYSUw8SyhKbiTh/IgO
            akjwV3gqTWpPpafV8RmVkNNBJg16F33adTKmnYLTBz8c7JlcToJM0ujsjpaJMYzU
            OjunoJmCRXrCTIi5E07xOqcSH46aEAloQhJdmY4nUyRwUOUS8rynPNU6OmQ+Owo6
            TtdiC4ZZ4b+wA3xzh4BsEsGnL1I/lJk7ZV3uBuHswXuvMOCu6baUi4/9DTVPR+sD
            j9Qu6fi3bVIue7FkY5z3xPz7PgRUkZZnpR2xYKMQytg2nrf/AaqXh7b5gE1Axp/y
            y+13kcJ3rDNq+rrBcPpv2Ha5+jEuLzlzb1Ug/iNcbqwsbFxfpDYt0dkKUsVdfaxw
            cQFolTEs0Gt8fESu3tSP6xnV5pRwcpWWRFa0HmpB+27/at+ltKxuqXXxvalrjth7
            V0oPvhyAyS/C60mO11xd+Gd/EMzHT5u4603kTjz/B4zq+sw6HULnLIBbUK9Py5LS
            UQEF0yTqGLBVIBaPSFIP62IgECyCiQMzJ+bEGvjZcZzj14HrWqJ8STLIbNm5Z2eG
            eIOXuTuz0F+Xj0ofzvVPLA1gYfrkY2LtEQha7AUREFsqrw==
            =imKa
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAh1cMc157aEmkInf/8lp1gaCUWkmfWUQX17bfApI0zrNA
            iVtXiGb7xVCOsxk3eoHY3MFepC1Cls4njJ2h7u4xWmC9GSTbrMstC1eoMltd2HQv
            AN0nFToXGziBQbuJR8S0OGAMZb8wNUba4fA/iSOqDCKlcCqQiPbovWqhq8FHUX2o
            n10cjtuOglbnnc+n4oeLSVRXmpxpEq9G1MiU1q+bifK87RvROeGGQi9zLFm8Fr1U
            b28U17hNhLvgiip45OuF7NK7KkUK/YSxNOae6JiJa9eHAjLHAV5DGCdnJakDLK0T
            vQsPqZR3PAJ/l69btdmDe3rCf/gME8AB2VG35rTvqFYQxkwZohdZDDxuGhWAGb0s
            b00v3XIPTwStqwBwkZVwU5lg+gEiaoW4g57bfLuQUKm5U0+bdcU/rfcT+Xs1Cegs
            4INh8ToV4F4kyDDZ8lYFJT5pJNVNyKMKy5C52OzpFzXPq3JZZfyw0+J2enD8dd1R
            YitsKADXFBY91HDCeT0Cecr6KJkZWjXLLlc8S550RSRJZIM1e1O5ZesKpy3g/ev4
            PnmRkAEFIoxS7M9q4rNht2SMurf95+xZisyhTIodgGzh78IYb5FDe4RBaCf+NxTE
            plR7vd3KDAsMG7ktQ7ZSfu00YdB34sWeFDGXUfVgtzCxzPvtcb9aZM2uApFzheTS
            UQFnflbYKfAcNHYGkxTkk7T/hqLQfLb5OafLeSa5sk32Caj2s1giYAQmfgc8oiSU
            v9JJEnm1eQ/mSiKd/d2wYXnwDaRnLr3gBjkQjRoIAHnQ7w==
            =v50j
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAsrqvMgbZ/DcNitVH2eADCofJ54qfZ5fZ+h/lHPIJTIRm
            m8NS+F0MQkNHLCvZgXf0Kbv32gtP0xuJiBJo6Fo35b8YeEx9uIv+P9pEoOWACZGO
            q/7ctdHGwytPLtYmeb8eGkyW+21nvghiTfn+e4wvJK5vF9eDD9FJ2OEp2tl5/BRe
            BhzvfF77wdhNF7Av3p8xfzp9bjFWZX4Em2scb7m3zuzX+UmQPNG4YlGOM2WHbKBu
            2Tkn4rDkx0SSWlhz8ubBzMKxoeh9kDaclhn7a6ShjYRpUYUxIOm+CCXAvrphshaN
            Xt7xhuAu+GINAcKblTw2BJg1Mao/LqsK9NCEU4cas/iCvWiIV03ze34svYKvlUsa
            Qxo7qbSmvo7DpF0qoLoF0fT6RJZFp9xrsW/5vFLcFE+KqknSlmgmMTIKjJcZ5zD6
            MMbT9XJ2xvYaZwckcYquwz/h/DyyJXTcUv+KhdkatC2MkhtzgyXPApXGOZKozeH1
            dF+4oRoEk6mVDC3e4AgPDpiJTZ8geIHe4QLnV3TrQJ5A1FrLfz7zHEr5Ss3qS+PB
            FkUHWF4Otg7DIpTGvruq7Wdc4JsjNseAg7mbFNAz11Ko+MoAG1EcS19A+DcCYFuO
            mvorI3Ih2ERnBW5g9uq69NIhYhTCX/iw3AyygdCwPamOtCTT/PqNhz2LbiPHcAbS
            UQHGtyU1YgAdsplrSOuSnjP6Rno4+AMhEbWbafX9CzbWS43JHz1Av08Ipg6PR9l5
            0daZhMdrA0Eb7mTWySCg2zTHh/TEpeQnwK+efxuEiSO5pQ==
            =0mRK
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ/+PqX4zK2KKz3SZQ/cXvV9tK3oceK2YPjCxdEr6cDS9ch+
            0JkqdiGCa5oSbn/pRof45NfLtGNfpJNa/G+cwQLhOF+DE9nCnukM3zCao0ib4UVy
            825PfRNTa63y9NNeLOktnIlldH9kMU+NrKlATF5aA6yfbIVZwnWzhc95BmmykXxq
            hppr3q12CME3+yZVxNkdHwN/OgpY54V6cQi1xU5bJEdvL1AcbjkledjaCOfsrwSa
            0wqoCB0bFnPQEzVZbNb+4xZWLqGU59Z1EffYV4NxCYp+6TllVh8kDG8aCy73Lype
            1ocNdeeXBYO6savIkLYjCtDuLbZXuG6enOhYSbya5AaOrz7gf9ZIBK1XTrasmc/x
            H2bHK3m8FXATKAoeCxJgCW+I7Q6QD98tfU5R6eOS1NMONSsZlaIiXXyTufwnjzRq
            QzdsvwhOFaatmP0SGnBe+osBhKB3qkBh51Tb4FGzFOCKCkWuKi0FuWUPqQ5nXTX6
            Bck3trn1C3/X+EZqlMEBvii4tdmR6TyMuEFtpU0uJnSNgvHpxcSAcyBaC2+D4/dP
            RL96nQ2EIF1uINvHpNe9p3X3JqcQsD9ZGQUhdIyfeK2/gqsaZfXHL8CTlMZFgN2A
            dzkSZdhIOK1nA13/ghpsDwtSPS/+VDHgcy1B1kAaxVCAU+Ow1dveA3oYyaU4lRjS
            UQGVMFce0E7gngipED+r1OwZ1+yXrS1xNyvJb862cTV2sIeqC4RamX+XhLboufOa
            O5IXj0qiA+J3LjkbzKu8knZs/3Un4S9eEK0pCmM2+JWJ5w==
            =dYbK
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQgAgSWBCE7nC3SWxtcG5xFBFXYa0qsEzmGH8Y++4aW6mIrN
            t3smKjsKYEBnY+vdMF/qHKhARGadLbupWrwImFQtLVtnGY3jfEntlyR9sXzKUDWq
            QAvk/hrH1Z3VIFODdwt1K3A/cy61ukYfmG0Rgh3zlKYp5Sj1X/FjG4t1KLirIvkZ
            SIVh7TAsnISmUBLNJ2iSFeN1eieg9RVd5on1VFsncuNWGi9UcKfjrLwtf39ETyNR
            3XAvI1iEu/Om4uZu8MNWw1muLKqOWGLS4zFrksSMyWApI6CS+NrNgqJJGqwmolVL
            GSRneHJQtEGc5vnJYk/wad0qbSchP1/ZOysoXDak4tJRAWkwOjTsZlN6y07WoREl
            kJQ9sP1VuKKUS35xgwoY6aq0wccuMTpmbCrnx4ubgfgyvBEfWMvTAR3p/RJvacyy
            fpw6FfaK4+yxCRDNYdQT/E2c
            =1TjS
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/9H/otByJkzUNkwTkVph4DK8YbBNizc8Upky+E7QBMbYPW
            U0U1OQWBqrABzySkaPT9LWE/IPl3nFNXka4nRA7cck712WB3JqaWFQdcJemRA/So
            K9rnvdbaT9InVToiWeLivXCH7qg+KhneJIl075GwJhVi1l32xia7L0zOU9HTJfBT
            O2wx0GOerObs1QKFJV80NdPgElV5frtR6gC9BKMlWc4Yi7khNvbbQJOBjuYe6y8s
            vjWGeLoQUOkLMXrS7nfTBXcNhPH9GSqZGfHK6J6T9Cf7oc2vqQavYVunlm9Xw9tY
            TlZdVAaMMTeaKUfMTjKrJFyeybvn7yEpcCVKs4xX25J2WY6JAilQnQmr6hbKRPc1
            YMB6pMsB65wtZJCLbltgBHCXOQJSnPFqBuF5Ohzxz9a+kNjSuU8fJOdDYqfKZkP3
            CdEhPMqskK5cDjzcyCi7Be601bFgak1f9G7xU6UMZLwBp6unQl2aCQNr2W3AiK4u
            pt+zwRGsjmhFwGZYzWgsIEo5vRLiuQdeDgrB2BqRNzzbHWTBN+khkebXSgRUSigf
            0tX7RtoYk0assfVSvo2aAjhxkVcDksVjEn2Iwe5/xCF3z1McgXiDUipqhm+ZvJGd
            WgQt8c5LAhFzbVRB56qoZD8gCFQPsyHNKAvSZkrrdgflIbVQN3G4sk3rhxV9eXHS
            UQGQBrwU1cr+SEN/F85WDqHc5aBrZRxiqIks/xknxNlIG03xXKMJWSC6Ng7JA4Jg
            uQl/G023wQVqk2QwgpJ69rtYBEsPOV1bxWC1cZ1HpIxtnQ==
            =kkKf
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ/9H3O9l54V/sOtemQW68YQbsquVVAIkIfn0ZO157N/D2M0
            i7Wcv331/Yqjw9eW2VzTkaB+P6oUftqlAMiq70Z6klPcf6EEkvFUELCl50jfNyzW
            A7d7+L6/y7Bpv908UHsppYuhoOmIIV/ZaQ45P+AReNX7LSCbYJK4LxB0NQne+W+8
            4k/zUrkyv7sQsTvq5Mn4TJ+MdT0c0biufF47IvaxpjTSFCJ9aaTglfCRintw4PE8
            7VdP8grcwTlH0WBuiVgZmeF/K0vsFqRNXKWP4JGm8QNJTu/YQObz97MusRYY5pGY
            NPdzSWLx8NeH4eHHfcmyVYRbZzyjEsVZmuKj7IPl0U60swCJYsX1AIvv6FDZHbYw
            Nqz9/9cvOLwkiERxH6VXVGmMlZaRNU3vER4RG8v28OiwlPA83Dk660HQKySWHSkP
            UOPkPDmsBn9YhSlqttd8ejuPhvrM9F7ke41NQbqV4W5joWOxivh2++CTxcryRdLC
            PxR+MYdnWs2+k7FDC54Grc1bEfItI9eEWqa2HcqqSfCpT/k/YSqKKznrygzErS2x
            Ogk9UQDBPemlWxSBW3ID7gHBd6Q/ZMxoTKrGgVMUTlGxwRf5l3HAH991zAkYpWN0
            sByyXECSbVyDL0+ZzxC4T/Bp5vxx8aGM9IH5UspG15dicvO9VcrHThKcRHvEsdrS
            UQEI9OLximYrV22nv6IWsesDfrlMwovLQMuzouT/xAQ5E2UzerlECXT7eoRoO5uZ
            bCDEdGiU+yDBoCR/+cDHRmSwxrpnSPX5y9J5NGmjK3Fi1g==
            =gsNQ
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2026-03-04T12:00:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdA+tE8cESOIYdZnK7mIqsf0b42LMHrfB7H93ouYZSMzDcw
            aKlWsp89BjR89LlF6IFC8/78vI/L+viBtoy4rJLaYKhbYdP+m5ZAeH3OtuknIxT9
            1FsBCQIQKxQa4rgGrlVs08+1Seer+z3F0NFsjz/8ywbkJWHvP78fAyjhsf7ZGjzi
            A6u2yYqeAk2qjzS2gIiKCOA3IQ3Mp7tadylqyJt55IueBee5TKC7js4obRii
            =GeuH
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
